/** Standalone OAuth 2.x client. All effects and application identity are explicit. */
export type { OAuthClient, OAuthClientAuthMethod, OAuthFetch, OAuthGrantKind, OAuthProviderDescriptor, OAuthRandomBytes, OAuthTokenSet, OAuthAppOptions, OAuthUrlGuard, OAuthHttpPorts, OAuthSleep, OAuthResource, OAuthTokenStore, TokenRefreshPort, ClientRegistrationCache, } from './ports.js';
export { OAuthError } from './errors.js';
export { isOAuthError, mapProviderErrorCode } from './api.js';
export type { OAuthErrorCode, OAuthErrorOptions } from './errors.js';
export { createPkcePair, deriveCodeChallenge, assertValidCodeVerifier } from './api.js';
export type { PkcePair } from './pkce.js';
export { DEFAULT_MAX_ENTRIES as PENDING_AUTHORIZATION_DEFAULT_MAX_ENTRIES, DEFAULT_TTL_MS as PENDING_AUTHORIZATION_DEFAULT_TTL_MS, STATE_BYTES as PENDING_AUTHORIZATION_STATE_BYTES, invalidState as invalidPendingAuthorizationState, } from './pending-authorizations.js';
export { secureEqualsForOwnerBinding } from './api.js';
export type { PendingAuthorization, PendingAuthorizationStore, PendingAuthorizationStoreDeps } from './pending-authorizations.js';
export { createOAuthUrlGuard } from './endpoint-safety.js';
export { assertSafeUserFacingUrl } from './api.js';
export type { OAuthUrlGuardOptions } from './endpoint-safety.js';
export { discoverAuthorizationServer, discoverProtectedResourceMetadata, fetchAuthorizationServerMetadata, parseResourceMetadataUrl, parseWwwAuthenticateScopes, } from './api.js';
export type { OAuthDiscoveryDeps, DiscoveredAuthorizationServer, DiscoveredOAuthConfiguration, DiscoverAuthorizationServerInput, DiscoveredProtectedResource, } from './discovery.js';
export { registerOAuthClientDynamically } from './api.js';
export type { DynamicClientRegistrationDeps, DynamicClientRegistrationInput, RegisteredOAuthClient } from './registration.js';
export { createOAuthClientRegistrar } from './registration-cache.js';
export type { OAuthClientRegistrar, OAuthClientRegistrarDeps, CachedRegistrationInput } from './registration-cache.js';
export { createFileClientRegistrationCache } from './file-registration-cache.js';
export type { RegistrationCacheFilePort, FileClientRegistrationCacheOptions } from './file-registration-cache.js';
export { createNodeRegistrationCacheFileIO } from './node-file-cache.js';
export { DEFAULT_TOKEN_REQUEST_TIMEOUT_MS } from './token-endpoint.js';
export { requestOAuthToken } from './api.js';
export type { TokenRequestDeps, TokenRequestInput } from './token-endpoint.js';
export { beginAuthorizationCode, completeAuthorizationCode } from './api.js';
export type { AuthorizationCallbackParams, BeginAuthorizationCodeDeps, BeginAuthorizationCodeInput, BeginAuthorizationCodeResult, CompleteAuthorizationCodeDeps, CompleteAuthorizationCodeInput, } from './authorization-code.js';
export { beginDeviceAuthorization, pollDeviceAuthorizationOnce } from './api.js';
export type { DeviceAuthorization, DeviceAuthorizationDeps, BeginDeviceAuthorizationInput, PollDeviceAuthorizationInput } from './device-code.js';
export { createTokenRefresher } from './refresh.js';
export { isTokenDueForRefresh, refreshAccessToken } from './api.js';
export type { TokenRefresher, TokenRefresherDeps, RefreshAccessTokenInput } from './refresh.js';
export { createOAuthProviderRegistry } from './registry.js';
export { buildOperatorOAuthProvider, assertValidOAuthProvider } from './api.js';
export type { OAuthProviderRegistry, OperatorOAuthProviderInput } from './registry.js';
export type { OAuthRequiredArgs, OAuthOptionalArgs, OAuthEmptyArgs } from './args.js';

export { createIssuerBoundDiscoveryPolicy } from './discovery-policy.js';
export type { OAuthDiscoveryPolicy } from './discovery-policy.js';
export { createDnsPinnedOAuthTransport } from './dns-pinned-transport.js';
export type { OAuthDnsAddress, OAuthDnsPort, OAuthAddressPolicyPort, OAuthDispatcherPort, OAuthDispatcherFactoryPort, DnsPinnedOAuthTransportDeps } from './dns-pinned-transport.js';
export { generateOAuthState } from './pkce.js';
export { buildOAuthAuthorizationUrl, exchangeOAuthAuthorizationCode } from './authorization-code.js';
export { createPendingAuthorizationStore } from './pending-authorizations.js';
export { redactOAuthUrls } from './redact.js';
export { defaultOAuthMessages } from './messages.js';
export type { OAuthMessages } from './messages.js';
export type { PendingAuthorizationCache, PendingAuthorizationScheduler, PendingAuthorizationCacheOptions } from './pending-authorizations.js';
export type { OAuthCodeExchangeInput } from './authorization-code.js';
export type { DnsPinnedOAuthTransport } from './dns-pinned-transport.js';
