import { describe, it, expect } from 'vitest';
import { createMemoryRolesApi } from '../adapters/memory.js';
import { createRolesController } from '../controllers/roles.controller.js';
import type { RolesApiPort } from '../ports.js';
const makeApi = () => createMemoryRolesApi({ workspaceId: 'w' }, { permissions: ['role.manage', 'content.read'] });
const deferred = <T>() => { let resolve!: (v: T) => void; let reject!: (v: unknown) => void; const promise = new Promise<T>((a, b) => { resolve = a; reject = b; }); return { promise, resolve, reject }; };
describe('roles controller', () => {
    it('loads both lists, creates and renames, and confirms role and policy deletion', async () => {
        const api = makeApi();
        const c = createRolesController({ api }, { permissions: ['role.manage'] });
        await c.load({});
        c.setDraft({ patch: { roleName: 'Authors', policyName: 'Read', policyDescription: 'read access' } });
        expect(await c.createRole({})).toBe(true);
        expect(await c.createPolicy({})).toBe(true);
        const role = c.getSnapshot().roles![0]!;
        const policy = c.getSnapshot().policies![0]!;
        c.editRole({ role });
        c.setDraft({ patch: { editingRoleName: 'Writers' } });
        expect(await c.saveRole({})).toBe(true);
        expect(c.getSnapshot().roles![0]!.name).toBe('Writers');
        c.editPolicy({ policy });
        c.setDraft({ patch: { editingPolicyName: 'Reader', editingPolicyDescription: '' } });
        expect(await c.savePolicy({})).toBe(true);
        expect(c.getSnapshot().policies![0]!.description).toBe('');
        c.requestDestructive({ target: { kind: 'role', role } });
        expect((await api.listRoles({})).roles).toHaveLength(1);
        c.cancelDestructive({});
        expect(await c.confirmDestructive({})).toBe(false);
        c.requestDestructive({ target: { kind: 'role', role } });
        expect(await c.confirmDestructive({})).toBe(true);
        c.requestDestructive({ target: { kind: 'policy', policy } });
        expect(await c.confirmDestructive({})).toBe(true);
        expect(c.getSnapshot().roles).toEqual([]);
        expect(c.getSnapshot().policies).toEqual([]);
        c.dispose({});
    });
    it('renders its data read-only by default and refuses every write without grants', async () => {
        const c = createRolesController({ api: makeApi() });
        await c.load({});
        c.setDraft({ patch: { roleName: 'blocked', policyName: 'blocked' } });
        expect(await c.createRole({})).toBe(false);
        expect(await c.createPolicy({})).toBe(false);
        expect(c.getSnapshot().roles).toEqual([]);
        expect(c.getSnapshot().rowError).toContain('permission');
        c.dispose({});
    });
    it('lists, grants and confirms removal of a scoped permission without reloading unrelated lists', async () => {
        const api = makeApi();
        const { policy } = await api.createPolicy({ name: 'Readers' });
        const c = createRolesController({ api }, { permissions: ['role.manage'] });
        await c.load({});
        await c.togglePermissions({ policyId: policy.id });
        c.setDraft({ patch: { permissionInput: 'content.read', resourceTypeInput: 'article' } });
        expect(await c.writePermission({})).toBe(true);
        const row = c.getSnapshot().permissionRows[0]!;
        expect(row.resourceType).toBe('article');
        c.requestDestructive({ target: { kind: 'permission', policyId: policy.id, row } });
        expect((await api.listPolicyPermissions({ policyId: policy.id })).policyPermissions).toHaveLength(1);
        expect(await c.confirmDestructive({})).toBe(true);
        expect(c.getSnapshot().permissionRows).toEqual([]);
        c.dispose({});
    });
    it('drops stale load failures and late results after closing a policy panel', async () => {
        const api = makeApi();
        const { policy: a } = await api.createPolicy({ name: 'a' });
        const { policy: b } = await api.createPolicy({ name: 'b' });
        const first = deferred<{
            policyPermissions: [
            ];
        }>();
        const second = deferred<{
            policyPermissions: [
            ];
        }>();
        const port: RolesApiPort = { ...api, listPolicyPermissions: ({ policyId }) => policyId === a.id ? first.promise : second.promise };
        const c = createRolesController({ api: port }, { permissions: ['role.manage'] });
        await c.load({});
        const pa = c.togglePermissions({ policyId: a.id });
        const pb = c.togglePermissions({ policyId: b.id });
        second.resolve({ policyPermissions: [] });
        await pb;
        first.reject(new Error('stale'));
        await pa;
        expect(c.getSnapshot().rowError).toBeNull();
        expect(c.getSnapshot().permissionPolicyId).toBe(b.id);
        await c.togglePermissions({ policyId: b.id });
        expect(c.getSnapshot().permissionsLoading).toBe(false);
        c.dispose({});
    });
    it('does not erase another panel draft or refresh its rows when an older grant settles', async () => {
        const api = makeApi();
        const { policy: a } = await api.createPolicy({ name: 'a' });
        const { policy: b } = await api.createPolicy({ name: 'b' });
        const gate = deferred<void>();
        const reads: string[] = [];
        const port: RolesApiPort = { ...api, writePolicyPermission: async (r, o) => { await gate.promise; return api.writePolicyPermission(r, o); }, listPolicyPermissions: (r, o) => { reads.push(r.policyId); return api.listPolicyPermissions(r, o); } };
        const c = createRolesController({ api: port }, { permissions: ['role.manage'] });
        await c.load({});
        await c.togglePermissions({ policyId: a.id });
        c.setDraft({ patch: { permissionInput: 'content.read' } });
        const pending = c.writePermission({});
        await c.togglePermissions({ policyId: b.id });
        c.setDraft({ patch: { permissionInput: 'new draft' } });
        gate.resolve();
        await pending;
        expect(reads).toEqual([a.id, b.id]);
        expect(c.getSnapshot().permissionInput).toBe('new draft');
        c.dispose({});
    });
    it('blocks duplicate confirmation and dismissal while pending; disposal aborts and prevents settlement', async () => {
        const api = makeApi();
        const { role } = await api.createRole({ name: 'r' });
        const gate = deferred<void>();
        let calls = 0;
        const c = createRolesController({ api: { ...api, deleteRole: async () => { calls++; await gate.promise; } } }, { permissions: ['role.manage'] });
        await c.load({});
        c.requestDestructive({ target: { kind: 'role', role } });
        const pending = c.confirmDestructive({});
        c.cancelDestructive({});
        expect(c.getSnapshot().pending).not.toBeNull();
        expect(await c.confirmDestructive({})).toBe(false);
        expect(calls).toBe(1);
        const before = c.getSnapshot();
        c.dispose({});
        gate.resolve();
        await pending;
        expect(c.getSnapshot()).toBe(before);
    });
});
