/**
 * Direct tests for the positional DDL builders in `transfer/internal-ddl.ts`. `script.test.ts`
 * reaches them through `runCopy` with one trivial table; these pin each statement exactly, including
 * the foreign-key omission rules and the 63-byte identifier fitting Postgres would otherwise do
 * silently (and ambiguously) itself.
 */
import { createHash } from "node:crypto";
import { describe, expect, it } from "vitest";
import {
  constraintSql, createTableSql, fitIdentifier, indexSql, qualified, quoteIdent, quoteLiteral, reseedIdentitySql,
} from "../../transfer/internal-ddl.js";
import type { TransferTable } from "../../transfer/types.js";

const sha8 = (text: string) => createHash("sha256").update(text).digest("hex").slice(0, 8);

function table(overrides: Partial<TransferTable> & { name: string }): TransferTable {
  return { columns: [{ name: "id", sqlType: "bigint", notNull: true }], primaryKey: ["id"], indexes: [], foreignKeys: [], checks: [], ...overrides };
}

describe("quoting", () => {
  it("doubles embedded quotes in identifiers and literals", () => {
    expect(quoteIdent('a"b')).toBe('"a""b"');
    expect(quoteLiteral("it's")).toBe("'it''s'");
    expect(qualified('s"x', "t")).toBe('"s""x"."t"');
  });
});

describe("fitIdentifier", () => {
  it("keeps a name of up to 63 bytes unchanged", () => {
    const exact = "a".repeat(63);
    expect(fitIdentifier(exact)).toBe(exact);
  });

  it("cuts a 64-byte name to 54 bytes plus _ and 8 hex chars of the whole name's SHA-256", () => {
    const long = "b".repeat(64);
    expect(fitIdentifier(long)).toBe(`${"b".repeat(54)}_${sha8(long)}`);
    expect(Buffer.byteLength(fitIdentifier(long))).toBe(63);
    expect(fitIdentifier(`${long}x`)).not.toBe(fitIdentifier(long));
  });

  it("counts multi-byte characters by bytes and never splits one", () => {
    const wide = "é".repeat(40); // 80 bytes
    const fitted = fitIdentifier(wide);
    expect(fitted).toBe(`${"é".repeat(27)}_${sha8(wide)}`);
    expect(Buffer.byteLength(fitted)).toBe(63);
  });
});

describe("createTableSql", () => {
  it("writes identity, default, NOT NULL and a composite primary key in column order", () => {
    const sql = createTableSql("copy", table({
      name: "rows",
      columns: [
        { name: "id", sqlType: "bigint", notNull: true, identity: "BY DEFAULT" },
        { name: "seq", sqlType: "integer", notNull: false, identity: "ALWAYS" },
        { name: "title", sqlType: "text", notNull: true, default: "''" },
        { name: "note", sqlType: "text", notNull: false },
      ],
      primaryKey: ["id", "seq"],
    }));
    expect(sql).toBe(
      'CREATE TABLE "copy"."rows" ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "seq" integer GENERATED ALWAYS AS IDENTITY, ' +
      `"title" text DEFAULT '' NOT NULL, "note" text, PRIMARY KEY ("id", "seq"));\n`,
    );
  });

  it("omits the PRIMARY KEY clause for a table without one", () => {
    expect(createTableSql("copy", table({ name: "log", primaryKey: [] }))).toBe('CREATE TABLE "copy"."log" ("id" bigint NOT NULL);\n');
  });
});

describe("reseedIdentitySql", () => {
  it("emits one setval per identity column (empty -> next 1, else max + 1) and nothing for plain columns", () => {
    const item = table({ name: "rows", columns: [
      { name: "id", sqlType: "bigint", notNull: true, identity: "ALWAYS" },
      { name: "plain", sqlType: "bigint", notNull: true },
    ] });
    const top = 'COALESCE((SELECT max("id") FROM "copy"."rows"), 0)';
    expect(reseedIdentitySql("copy", item)).toBe(
      `DO $transfer$ BEGIN PERFORM setval(pg_get_serial_sequence('"copy"."rows"', 'id'), GREATEST(${top}, 1), ${top} >= 1); END $transfer$;\n`,
    );
    expect(reseedIdentitySql("copy", item, "host")).toContain("DO $host$ BEGIN");
    expect(reseedIdentitySql("copy", table({ name: "rows" }))).toBe("");
  });
});

describe("indexSql", () => {
  it("writes unique and plain indexes with fitted names", () => {
    const longName = `idx_${"x".repeat(70)}`;
    const sql = indexSql("copy", table({ name: "rows", indexes: [
      { name: "rows_slug", columns: ["slug"], unique: true },
      { name: longName, columns: ["a", "b"], unique: false },
    ] }));
    expect(sql).toBe(
      'CREATE UNIQUE INDEX "rows_slug" ON "copy"."rows" ("slug");\n' +
      `CREATE INDEX "${fitIdentifier(longName)}" ON "copy"."rows" ("a", "b");\n`,
    );
  });
});

describe("constraintSql", () => {
  const parent = table({ name: "parent", primaryKey: ["id"], indexes: [{ name: "parent_code", columns: ["code", "region"], unique: true }, { name: "parent_plain", columns: ["label"], unique: false }] });

  it("with no constraints writes only the session-local marker table", () => {
    expect(constraintSql("copy", [parent], "pg_temp.unchecked")).toBe('CREATE TEMP TABLE "unchecked" (name text NOT NULL) ON COMMIT DROP;\n');
  });

  it("adds CHECKs then keys NOT VALID, and validates each one with its own exception handler", () => {
    const child = table({
      name: "child",
      checks: [{ name: "child_positive", sql: '"id" > 0' }],
      foreignKeys: [{ name: "child_parent", columns: ["parent_id"], foreignTable: "parent", foreignColumns: null, onDelete: "cascade", onUpdate: "bogus" }],
    });
    expect(constraintSql("copy", [parent, child], "pg_temp.unchecked", "host")).toBe(
      'CREATE TEMP TABLE "unchecked" (name text NOT NULL) ON COMMIT DROP;\n' +
      'ALTER TABLE "copy"."child" ADD CONSTRAINT "child_positive" CHECK ("id" > 0) NOT VALID;\n' +
      'ALTER TABLE "copy"."child" ADD CONSTRAINT "child_parent" FOREIGN KEY ("parent_id") REFERENCES "copy"."parent" ("id") ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;\n' +
      "DO $host$ BEGIN\n" +
      '  BEGIN ALTER TABLE "copy"."child" VALIDATE CONSTRAINT "child_positive";\n' +
      `  EXCEPTION WHEN foreign_key_violation OR check_violation THEN INSERT INTO "pg_temp"."unchecked" VALUES ('child.child_positive'); END;\n` +
      '  BEGIN ALTER TABLE "copy"."child" VALIDATE CONSTRAINT "child_parent";\n' +
      `  EXCEPTION WHEN foreign_key_violation OR check_violation THEN INSERT INTO "pg_temp"."unchecked" VALUES ('child.child_parent'); END;\n` +
      "END $host$;\n",
    );
  });

  it("keeps every documented referential action and maps anything else to NO ACTION", () => {
    for (const action of ["no action", "RESTRICT", "Cascade", "SET NULL", "set default"]) {
      const child = table({ name: "child", foreignKeys: [{ name: "fk", columns: ["p"], foreignTable: "parent", foreignColumns: ["id"], onDelete: action, onUpdate: action }] });
      expect(constraintSql("copy", [parent, child], "u")).toContain(`ON DELETE ${action.toUpperCase()} ON UPDATE ${action.toUpperCase()} NOT VALID`);
    }
  });

  it("references a unique index's columns in any order, but leaves out keys Postgres would reject", () => {
    const fk = (name: string, foreignTable: string, columns: string[], foreignColumns: string[] | null) =>
      ({ name, columns, foreignTable, foreignColumns, onDelete: "NO ACTION", onUpdate: "NO ACTION" });
    const child = table({ name: "child", foreignKeys: [
      fk("by_unique", "parent", ["c", "r"], ["region", "code"]),
      fk("missing_parent", "logins", ["login_id"], null),
      fk("non_unique", "parent", ["l"], ["label"]),
      fk("arity", "parent", ["a", "b"], null),
    ] });
    const sql = constraintSql("copy", [parent, child], "u");
    expect(sql).toContain('ADD CONSTRAINT "by_unique" FOREIGN KEY ("c", "r") REFERENCES "copy"."parent" ("region", "code")');
    expect(sql).not.toContain("missing_parent");
    expect(sql).not.toContain("non_unique");
    expect(sql).not.toContain('"arity"');
  });

  it("fits long constraint names and records the fitted name in the unvalidated marker", () => {
    const longCheck = `check_${"z".repeat(70)}`;
    const sql = constraintSql("copy", [table({ name: "t", checks: [{ name: longCheck, sql: "true" }] })], "u");
    const fitted = fitIdentifier(longCheck);
    expect(sql).toContain(`ADD CONSTRAINT "${fitted}" CHECK (true) NOT VALID`);
    expect(sql).toContain(`INSERT INTO "u" VALUES ('t.${fitted}')`);
    expect(sql.startsWith('CREATE TEMP TABLE "u" ')).toBe(true);
  });
});
