import assert from "node:assert/strict";
import { test } from "vitest";
import { uploadMedia, updateMediaMetadata, trashMedia } from "../media-service.js";
import { InMemoryMediaRepo, InMemoryAssetBlobRepo, InMemoryAssetRenditionRepo } from "../repo.memory.js";
import { InMemoryBlobStore } from "../blob-store.memory.js";

/** Owner dispatch 2026-10-04: asset attribution is independent of deduplicated blob ownership. */
test("createdBy stamps each acting principal despite sharing a blob, and survives editorial/status edits", async () => {
  let id = 0;
  const deps = {
    clock: { nowMs: () => Date.parse("2026-10-04T00:00:00Z") },
    idGen: { newId: () => `creator-test-${++id}` },
    mediaRepo: new InMemoryMediaRepo({}), blobRepo: new InMemoryAssetBlobRepo({}),
    renditionRepo: new InMemoryAssetRenditionRepo({}), blobStore: new InMemoryBlobStore(),
  };
  const media = [];
  for (const principal of ["owner", "user-2", "agent-3", "plugin-4"]) {
    const result = await uploadMedia({ deps, input: { workspaceId: "ws", bytes: new Uint8Array([1, 2, 3]),
      filename: `${principal}.png`, contentType: "image/png", createdByPrincipal: principal } });
    assert.equal(result.media.createdBy, principal);
    assert.equal((await deps.mediaRepo.findById({ workspaceId: "ws", id: result.media.id }))?.createdBy, principal);
    media.push(result.media);
  }
  assert.equal(new Set(media.map(row => row.source.sha256)).size, 1);
  assert.equal((await deps.blobRepo.list({ workspaceId: "ws" })).length, 1);
  assert.equal((await deps.blobRepo.list({ workspaceId: "ws" }))[0]?.createdByPrincipal, "owner");
  const edited = await updateMediaMetadata({ deps, input: { workspaceId: "ws", id: media[1]!.id,
    credit: "Generated by another producer", title: "Renamed" } });
  assert.equal(edited.media.createdBy, "user-2");
  const trashed = await trashMedia({ deps, input: { workspaceId: "ws", id: media[1]!.id } });
  assert.equal(trashed.media.createdBy, "user-2");
  await deps.mediaRepo.save({ ...trashed.media, createdBy: "spoofed-on-update" });
  assert.equal((await deps.mediaRepo.findById({ workspaceId: "ws", id: trashed.media.id }))?.createdBy, "user-2");
});
