/**
 * @module connectors
 *
 * `POST/GET /api/connectors/{auth,storage,payments,db,realtime}/...` — JSON transport over five
 * narrow provider ports. The ports live here because they are the exact behavior this transport
 * consumes; concrete adapters such as `@jini-ai/capability-providers` satisfy them structurally at a
 * product composition root. That dependency direction is deliberate: the daemon route pack must not
 * point down into an incubating implementation package.
 *
 * **SEC-005 throughout**: every provider call is wrapped so a raw Stripe/SQL/JWT/WebSocket error
 * never reaches the HTTP caller verbatim — matching `media.ts`/`delegated-tools.ts`'s
 * `reportInternalError` precedent exactly (a correlation-id-bearing generic `INTERNAL_ERROR`, the
 * real error only reaching a host-owned sink).
 *
 * **`NOT_CONFIGURED` (503)**: every route's very first check is whether its one required
 * capability slot (`deps.auth`/`deps.storage`/`deps.payments`/`deps.db`/`deps.realtime`) is even
 * supplied — all five are independently optional on {@link ConnectorsHttpDeps}, and
 * `@jini-ai/server`'s zero-config default (see that package's `create-local-node-daemon.ts` wiring)
 * leaves every slot unconfigured. A request against an unconfigured capability gets a clean 503
 * before touching anything else, never a crash or a fabricated result — the same "capability exists
 * and is reachable but inert until a host configures it" shape `host-tools.ts#denyAllWorkspaceRoots`/
 * `db-ops.ts#denyAllDaemonDbPolicy` already established for other zero-config-default route packs.
 *
 * **Wire shapes, chosen for this route pack specifically (the ports themselves have no opinion on
 * HTTP transport):**
 * - `StorageProvider.put`/`.get` deal in raw `Uint8Array` — JSON has no binary type, so this pack
 *   base64-encodes on the wire (`dataBase64` request/response field), the same encoding
 *   `media.ts#runMediaGenerationInBackground` already uses for generated bytes.
 * - `AuthProvider.verifySession` takes a bearer token; the session-verification route accepts it in
 *   a POST JSON body. Credentials do not belong in URLs, where browser history, reverse proxies,
 *   and access logs commonly retain them.
 * - `DbProvider.query`'s optional `where` filter is a JSON-encoded string in the `?where=` query
 *   parameter (`{"status":"active"}`), decoded and validated as a plain object before being handed
 *   to the provider.
 * - `RealtimeProvider.subscribe` has no route here — see the realtime section below for why.
 */
import { randomUUID } from 'node:crypto';
import type { Express } from 'express';
import { createApiError } from '@jini-ai/protocol';
import { defineJsonRoute, mountJsonRoute, type AdapterContext } from '@jini-ai/http-kit';
import { validationError } from '@jini-ai/http-kit';
import { err, ok, type Result, type RouteInputContext } from '@jini-ai/http-kit';

export interface AuthCredentials {
  readonly email: string;
  readonly password: string;
}

export interface AuthUser {
  readonly id: string;
  readonly email: string;
  readonly createdAt: number;
}

export interface AuthSession {
  readonly token: string;
  readonly userId: string;
  readonly expiresAt: number;
}

export interface AuthProvider {
  signUp(credentials: AuthCredentials): Promise<AuthUser>;
  signIn(credentials: AuthCredentials): Promise<AuthSession>;
  signOut({ token }: { readonly token: string }, _optional?: Record<string, never>): Promise<void>;
  verifySession({ token }: { readonly token: string }, _optional?: Record<string, never>): Promise<AuthUser | null>;
}

export interface StoragePutOptions {
  readonly contentType?: string;
}

export interface StorageObjectMeta {
  readonly key: string;
  readonly size: number;
  readonly contentType?: string;
  readonly updatedAt: number;
}

export interface StorageProvider {
  put({ key, data }: { readonly key: string; readonly data: Uint8Array }, options?: StoragePutOptions): Promise<StorageObjectMeta>;
  get({ key }: { readonly key: string }, _optional?: Record<string, never>): Promise<Uint8Array | null>;
  delete({ key }: { readonly key: string }, _optional?: Record<string, never>): Promise<void>;
  list(_required: Record<string, never>, optionalArgs?: { readonly prefix?: string | undefined }): Promise<StorageObjectMeta[]>;
}

export interface ChargeInput {
  readonly amountCents: number;
  readonly currency: string;
  readonly customerRef: string;
  readonly description?: string;
}

export type ChargeStatus = 'pending' | 'succeeded' | 'failed' | 'refunded';

export interface Charge {
  readonly id: string;
  readonly status: ChargeStatus;
  readonly amountCents: number;
  readonly currency: string;
  readonly customerRef: string;
  readonly createdAt: number;
}

export interface PaymentsProvider {
  charge(requiredArgs: Omit<ChargeInput, 'description'>, optionalArgs?: Pick<ChargeInput, 'description'>): Promise<Charge>;
  getCharge({ id }: { readonly id: string }, _optional?: Record<string, never>): Promise<Charge | null>;
  refund({ id }: { readonly id: string }, _optional?: Record<string, never>): Promise<Charge>;
}

export interface DbRecord {
  readonly id: string;
  readonly [field: string]: unknown;
}

export interface DbQuery {
  readonly where?: Readonly<Record<string, unknown>>;
}

export interface DbProvider {
  insert({ collection, record }: { readonly collection: string; readonly record: DbRecord }, _optional?: Record<string, never>): Promise<DbRecord>;
  get({ collection, id }: { readonly collection: string; readonly id: string }, _optional?: Record<string, never>): Promise<DbRecord | null>;
  update({ collection, id, patch }: { readonly collection: string; readonly id: string; readonly patch: Readonly<Record<string, unknown>> }, _optional?: Record<string, never>): Promise<DbRecord | null>;
  delete({ collection, id }: { readonly collection: string; readonly id: string }, _optional?: Record<string, never>): Promise<void>;
  query({ collection }: { readonly collection: string }, query?: DbQuery): Promise<DbRecord[]>;
}

export interface RealtimeProvider {
  publish<T>({ channel, event }: { readonly channel: string; readonly event: T }, _optional?: Record<string, never>): Promise<void>;
  subscribe<T>({ channel, handler }: { readonly channel: string; readonly handler: (required: { event: T }) => void }, _optional?: Record<string, never>): () => void;
}

export interface ConnectorsInternalErrorContext {
  readonly source: 'auth' | 'storage' | 'payments' | 'db' | 'realtime';
  readonly operation: string;
  readonly correlationId: string;
  readonly error: unknown;
}

export interface ConnectorsHttpDeps {
  readonly auth?: AuthProvider;
  readonly storage?: StorageProvider;
  readonly payments?: PaymentsProvider;
  readonly db?: DbProvider;
  readonly realtime?: RealtimeProvider;
  /** Host-owned sink for the real exception behind a generic `INTERNAL_ERROR` response (SEC-005). Defaults to `console.error`. */
  readonly onInternalError?: (context: ConnectorsInternalErrorContext) => void;
}

function defaultInternalErrorSink(context: ConnectorsInternalErrorContext): void {
  // eslint-disable-next-line no-console
  console.error(`[@jini-ai/http-kit] internal error (connectors/${context.source}.${context.operation}, correlationId=${context.correlationId})`, context.error);
}

function notConfiguredError(capability: string): ReturnType<typeof createApiError> {
  return createApiError({ code: 'NOT_CONFIGURED', message: `${capability} provider not configured` });
}

/** Runs one provider call, converting any thrown error into a redacted, correlation-id-bearing `INTERNAL_ERROR` (SEC-005) instead of letting it reach the HTTP caller verbatim. */
async function guardedCall<T>(
  deps: ConnectorsHttpDeps,
  source: ConnectorsInternalErrorContext['source'],
  operation: string,
  fn: () => Promise<T>,
): Promise<Result<T>> {
  try {
    return ok({ value: await fn() });
  } catch (error) {
    const correlationId = randomUUID();
    const sink = deps.onInternalError ?? defaultInternalErrorSink;
    sink({ source, operation, correlationId, error });
    return err({ error: createApiError({ code: 'INTERNAL_ERROR', message: 'an internal error occurred' }, { requestId: correlationId }) });
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function nonEmptyString(value: unknown): string | null {
  return typeof value === 'string' && value.trim().length > 0 ? value : null;
}

function firstQueryValue(raw: unknown): string | undefined {
  const value = Array.isArray(raw) ? raw[0] : raw;
  return typeof value === 'string' ? value : undefined;
}

// ---------------------------------------------------------------------------
// auth
// ---------------------------------------------------------------------------

function parseAuthCredentials(input: RouteInputContext): Result<AuthCredentials> {
  if (!isRecord(input.body)) return err({ error: validationError({ message: 'body must be a JSON object' }) });
  const email = nonEmptyString(input.body.email);
  if (!email) return err({ error: validationError({ message: 'email must be a non-empty string' }, { issues: [{ path: 'email', message: 'required non-empty string' }] }) });
  const password = nonEmptyString(input.body.password);
  if (!password) return err({ error: validationError({ message: 'password must be a non-empty string' }, { issues: [{ path: 'password', message: 'required non-empty string' }] }) });
  return ok({ value: { email, password } });
}

function parseAuthToken(input: RouteInputContext): Result<string> {
  if (!isRecord(input.body)) return err({ error: validationError({ message: 'body must be a JSON object' }) });
  const token = nonEmptyString(input.body.token);
  if (!token) return err({ error: validationError({ message: 'token must be a non-empty string' }, { issues: [{ path: 'token', message: 'required non-empty string' }] }) });
  return ok({ value: token });
}

export interface ConnectorsAuthUserResponse {
  readonly user: AuthUser;
}

export interface ConnectorsAuthSessionResponse {
  readonly session: AuthSession;
}

export interface ConnectorsAuthVerifyResponse {
  readonly user: AuthUser | null;
}

export interface ConnectorsOkResponse {
  readonly ok: true;
}

export const connectorsAuthSignUpRoute = defineJsonRoute<AuthCredentials, ConnectorsAuthUserResponse, ConnectorsHttpDeps>({
  method: 'post', path: '/api/connectors/auth/signup', parse: parseAuthCredentials, handle: async ({ input: credentials, deps }) => {
    if (!deps.auth) return err({ error: notConfiguredError('auth') });
    const result = await guardedCall(deps, 'auth', 'signUp', () => deps.auth!.signUp(credentials));
    return result.ok ? ok({ value: { user: result.value } }) : result;
  }
}, { requireSameOrigin: true, successStatus: 201 });

export const connectorsAuthSignInRoute = defineJsonRoute<AuthCredentials, ConnectorsAuthSessionResponse, ConnectorsHttpDeps>({
  method: 'post', path: '/api/connectors/auth/signin', parse: parseAuthCredentials, handle: async ({ input: credentials, deps }) => {
    if (!deps.auth) return err({ error: notConfiguredError('auth') });
    const result = await guardedCall(deps, 'auth', 'signIn', () => deps.auth!.signIn(credentials));
    return result.ok ? ok({ value: { session: result.value } }) : result;
  }
}, { requireSameOrigin: true });

export const connectorsAuthSignOutRoute = defineJsonRoute<string, ConnectorsOkResponse, ConnectorsHttpDeps>({
  method: 'post', path: '/api/connectors/auth/signout', parse: parseAuthToken, handle: async ({ input: token, deps }) => {
    if (!deps.auth) return err({ error: notConfiguredError('auth') });
    const result = await guardedCall(deps, 'auth', 'signOut', () => deps.auth!.signOut({ token }));
    return result.ok ? ok({ value: { ok: true } }) : result;
  }
}, { requireSameOrigin: true });

export const connectorsAuthSessionRoute = defineJsonRoute<string, ConnectorsAuthVerifyResponse, ConnectorsHttpDeps>({
  method: 'post', path: '/api/connectors/auth/session', parse: parseAuthToken, handle: async ({ input: token, deps }) => {
    if (!deps.auth) return err({ error: notConfiguredError('auth') });
    const result = await guardedCall(deps, 'auth', 'verifySession', () => deps.auth!.verifySession({ token }));
    return result.ok ? ok({ value: { user: result.value } }) : result;
  }
}, { requireSameOrigin: true });

// ---------------------------------------------------------------------------
// storage
// ---------------------------------------------------------------------------

function parseStorageKey(input: RouteInputContext): Result<string> {
  const key = input.params.key;
  return typeof key === 'string' && key.length > 0 ? ok({ value: key }) : err({ error: validationError({ message: 'key must be a non-empty path parameter' }) });
}

interface StoragePutRequest {
  readonly key: string;
  readonly dataBase64: string;
  readonly contentType?: string;
}

/**
 * Strict base64 well-formedness check.
 *
 * `Buffer.from(value, 'base64')` cannot be used as the validator here because it never rejects
 * anything: it silently skips every character outside the alphabet and returns whatever it managed
 * to decode. `"!!!!"` decodes to zero bytes, and a payload truncated in transit decodes to a
 * shorter one — both of which would then be written over whatever already lived at that key. A
 * storage `put` that quietly persists the wrong bytes is worse than one that refuses them, so this
 * insists on a canonical encoding: alphabet only, at most two trailing pad characters, a length
 * that is a whole number of 4-character groups, and at least one real data character.
 */
const BASE64_PATTERN = /^[A-Za-z0-9+/]+={0,2}$/;

function isWellFormedBase64(value: string): boolean {
  if (value.length === 0 || value.length % 4 !== 0) return false;
  return BASE64_PATTERN.test(value);
}

function parseStoragePut(input: RouteInputContext): Result<StoragePutRequest> {
  const keyResult = parseStorageKey(input);
  if (!keyResult.ok) return keyResult;
  if (!isRecord(input.body)) return err({ error: validationError({ message: 'body must be a JSON object' }) });
  const dataBase64 = input.body.dataBase64;
  if (typeof dataBase64 !== 'string' || !isWellFormedBase64(dataBase64)) {
    return err({ error: validationError({ message: 'dataBase64 must be a non-empty base64-encoded string' }, { issues: [{ path: 'dataBase64', message: 'required base64 string' }] }) });
  }
  const contentType = input.body.contentType;
  if (contentType !== undefined && typeof contentType !== 'string') {
    return err({ error: validationError({ message: 'contentType must be a string when provided' }) });
  }
  return ok({ value: { key: keyResult.value, dataBase64, ...(contentType !== undefined ? { contentType: contentType as string } : {}) } });
}

function parseStorageListQuery(input: RouteInputContext): Result<string | undefined> {
  const prefix = firstQueryValue(input.query.prefix);
  return ok({ value: prefix });
}

export interface ConnectorsStorageMetaResponse {
  readonly object: StorageObjectMeta;
}

export interface ConnectorsStorageGetResponse {
  readonly dataBase64: string;
}

export interface ConnectorsStorageListResponse {
  readonly objects: readonly StorageObjectMeta[];
}

export const connectorsStoragePutRoute = defineJsonRoute<StoragePutRequest, ConnectorsStorageMetaResponse, ConnectorsHttpDeps>({
  method: 'put', path: '/api/connectors/storage/:key', parse: parseStoragePut, handle: async ({ input: { key, dataBase64, contentType }, deps }) => {
    if (!deps.storage) return err({ error: notConfiguredError('storage') });
    const options: StoragePutOptions | undefined = contentType !== undefined ? { contentType } : undefined;
    const result = await guardedCall(deps, 'storage', 'put', () =>
      deps.storage!.put({ key, data: Buffer.from(dataBase64, 'base64') }, options),
    );
    return result.ok ? ok({ value: { object: result.value } }) : result;
  }
}, { requireSameOrigin: true });

export const connectorsStorageGetRoute = defineJsonRoute<string, ConnectorsStorageGetResponse, ConnectorsHttpDeps>({
  method: 'get', path: '/api/connectors/storage/:key', parse: parseStorageKey, handle: async ({ input: key, deps }) => {
    if (!deps.storage) return err({ error: notConfiguredError('storage') });
    const result = await guardedCall(deps, 'storage', 'get', () => deps.storage!.get({ key }));
    if (!result.ok) return result;
    if (result.value === null) return err({ error: createApiError({ code: 'NOT_FOUND', message: 'storage object not found' }) });
    return ok({ value: { dataBase64: Buffer.from(result.value).toString('base64') } });
  }
});

export const connectorsStorageDeleteRoute = defineJsonRoute<string, ConnectorsOkResponse, ConnectorsHttpDeps>({
  method: 'delete', path: '/api/connectors/storage/:key', parse: parseStorageKey, handle: async ({ input: key, deps }) => {
    if (!deps.storage) return err({ error: notConfiguredError('storage') });
    const result = await guardedCall(deps, 'storage', 'delete', () => deps.storage!.delete({ key }));
    return result.ok ? ok({ value: { ok: true } }) : result;
  }
}, { requireSameOrigin: true });

export const connectorsStorageListRoute = defineJsonRoute<string | undefined, ConnectorsStorageListResponse, ConnectorsHttpDeps>({
  method: 'get', path: '/api/connectors/storage', parse: parseStorageListQuery, handle: async ({ input: prefix, deps }) => {
    if (!deps.storage) return err({ error: notConfiguredError('storage') });
    const result = await guardedCall(deps, 'storage', 'list', () => deps.storage!.list({}, { prefix }));
    return result.ok ? ok({ value: { objects: result.value } }) : result;
  }
});

// ---------------------------------------------------------------------------
// payments
// ---------------------------------------------------------------------------

function parseChargeInput(input: RouteInputContext): Result<ChargeInput> {
  if (!isRecord(input.body)) return err({ error: validationError({ message: 'body must be a JSON object' }) });
  const amountCents = input.body.amountCents;
  // Cents are a whole, positive unit. `isFinite` alone let `-125.5` reach `payments.charge()`,
  // where a negative amount is a refund nobody requested and a fractional one is rounded by the
  // provider in a way the caller cannot predict — and neither is recoverable once the charge
  // exists. `isSafeInteger` also rejects magnitudes past the point where JSON round-trips stop
  // being exact, which at a money boundary is a value nobody should be allowed to guess at.
  if (typeof amountCents !== 'number' || !Number.isSafeInteger(amountCents) || amountCents <= 0) {
    return err({ error: validationError({ message: 'amountCents must be a positive whole number of cents' }, { issues: [{ path: 'amountCents', message: 'required positive integer' }] }) });
  }
  const currency = nonEmptyString(input.body.currency);
  if (!currency) return err({ error: validationError({ message: 'currency must be a non-empty string' }, { issues: [{ path: 'currency', message: 'required non-empty string' }] }) });
  const customerRef = nonEmptyString(input.body.customerRef);
  if (!customerRef) {
    return err({ error: validationError({ message: 'customerRef must be a non-empty string' }, { issues: [{ path: 'customerRef', message: 'required non-empty string' }] }) });
  }
  const description = input.body.description;
  if (description !== undefined && typeof description !== 'string') {
    return err({ error: validationError({ message: 'description must be a string when provided' }) });
  }
  return ok({ value: { amountCents, currency, customerRef, ...(description !== undefined ? { description: description as string } : {}) } });
}

function parseChargeId(input: RouteInputContext): Result<string> {
  const id = input.params.id;
  return typeof id === 'string' && id.length > 0 ? ok({ value: id }) : err({ error: validationError({ message: 'id must be a non-empty path parameter' }) });
}

export interface ConnectorsChargeResponse {
  readonly charge: Charge;
}

export const connectorsPaymentsChargeRoute = defineJsonRoute<ChargeInput, ConnectorsChargeResponse, ConnectorsHttpDeps>({
  method: 'post', path: '/api/connectors/payments/charge', parse: parseChargeInput, handle: async ({ input, deps }) => {
    if (!deps.payments) return err({ error: notConfiguredError('payments') });
    const { description, ...required } = input;
    const result = await guardedCall(deps, 'payments', 'charge', () => deps.payments!.charge(required, description === undefined ? {} : { description }));
    return result.ok ? ok({ value: { charge: result.value } }) : result;
  }
}, { requireSameOrigin: true, successStatus: 201 });

export const connectorsPaymentsGetRoute = defineJsonRoute<string, ConnectorsChargeResponse, ConnectorsHttpDeps>({
  method: 'get', path: '/api/connectors/payments/:id', parse: parseChargeId, handle: async ({ input: id, deps }) => {
    if (!deps.payments) return err({ error: notConfiguredError('payments') });
    const result = await guardedCall(deps, 'payments', 'getCharge', () => deps.payments!.getCharge({ id }));
    if (!result.ok) return result;
    if (result.value === null) return err({ error: createApiError({ code: 'NOT_FOUND', message: 'charge not found' }) });
    return ok({ value: { charge: result.value } });
  }
});

export const connectorsPaymentsRefundRoute = defineJsonRoute<string, ConnectorsChargeResponse, ConnectorsHttpDeps>({
  method: 'post', path: '/api/connectors/payments/:id/refund', parse: parseChargeId, handle: async ({ input: id, deps }) => {
    if (!deps.payments) return err({ error: notConfiguredError('payments') });
    const result = await guardedCall(deps, 'payments', 'refund', () => deps.payments!.refund({ id }));
    return result.ok ? ok({ value: { charge: result.value } }) : result;
  }
}, { requireSameOrigin: true });

// ---------------------------------------------------------------------------
// db
// ---------------------------------------------------------------------------

function parseDbCollection(input: RouteInputContext): Result<string> {
  const collection = input.params.collection;
  return typeof collection === 'string' && collection.length > 0
    ? ok({ value: collection })
    : err({ error: validationError({ message: 'collection must be a non-empty path parameter' }) });
}

interface DbInsertRequest {
  readonly collection: string;
  readonly record: DbRecord;
}

function parseDbInsert(input: RouteInputContext): Result<DbInsertRequest> {
  const collectionResult = parseDbCollection(input);
  if (!collectionResult.ok) return collectionResult;
  if (!isRecord(input.body)) return err({ error: validationError({ message: 'body must be a JSON object' }) });
  const id = input.body.id;
  if (typeof id !== 'string' || id.length === 0) {
    return err({ error: validationError({ message: 'id must be a non-empty string field' }, { issues: [{ path: 'id', message: 'required non-empty string' }] }) });
  }
  return ok({ value: { collection: collectionResult.value, record: input.body as unknown as DbRecord } });
}

interface DbCollectionIdParams {
  readonly collection: string;
  readonly id: string;
}

function parseDbCollectionId(input: RouteInputContext): Result<DbCollectionIdParams> {
  const collectionResult = parseDbCollection(input);
  if (!collectionResult.ok) return collectionResult;
  const id = input.params.id;
  if (typeof id !== 'string' || id.length === 0) return err({ error: validationError({ message: 'id must be a non-empty path parameter' }) });
  return ok({ value: { collection: collectionResult.value, id } });
}

interface DbUpdateRequest extends DbCollectionIdParams {
  readonly patch: Readonly<Record<string, unknown>>;
}

function parseDbUpdate(input: RouteInputContext): Result<DbUpdateRequest> {
  const parsed = parseDbCollectionId(input);
  if (!parsed.ok) return parsed;
  if (!isRecord(input.body)) return err({ error: validationError({ message: 'body must be a JSON object' }) });
  return ok({ value: { ...parsed.value, patch: input.body } });
}

interface DbQueryRequest {
  readonly collection: string;
  readonly query?: DbQuery;
}

function parseDbQueryRequest(input: RouteInputContext): Result<DbQueryRequest> {
  const collectionResult = parseDbCollection(input);
  if (!collectionResult.ok) return collectionResult;
  const whereRaw = firstQueryValue(input.query.where);
  if (whereRaw === undefined) return ok({ value: { collection: collectionResult.value } });
  let parsedWhere: unknown;
  try {
    parsedWhere = JSON.parse(whereRaw);
  } catch {
    return err({ error: validationError({ message: 'where must be valid JSON when provided' }) });
  }
  if (!isRecord(parsedWhere)) return err({ error: validationError({ message: 'where must be a JSON object when provided' }) });
  return ok({ value: { collection: collectionResult.value, query: { where: parsedWhere } } });
}

export interface ConnectorsDbRecordResponse {
  readonly record: DbRecord;
}

export interface ConnectorsDbQueryResponse {
  readonly records: readonly DbRecord[];
}

export const connectorsDbInsertRoute = defineJsonRoute<DbInsertRequest, ConnectorsDbRecordResponse, ConnectorsHttpDeps>({
  method: 'post', path: '/api/connectors/db/:collection', parse: parseDbInsert, handle: async ({ input: { collection, record }, deps }) => {
    if (!deps.db) return err({ error: notConfiguredError('db') });
    const result = await guardedCall(deps, 'db', 'insert', () => deps.db!.insert({ collection, record }));
    return result.ok ? ok({ value: { record: result.value } }) : result;
  }
}, { requireSameOrigin: true, successStatus: 201 });

export const connectorsDbGetRoute = defineJsonRoute<DbCollectionIdParams, ConnectorsDbRecordResponse, ConnectorsHttpDeps>({
  method: 'get', path: '/api/connectors/db/:collection/:id', parse: parseDbCollectionId, handle: async ({ input: { collection, id }, deps }) => {
    if (!deps.db) return err({ error: notConfiguredError('db') });
    const result = await guardedCall(deps, 'db', 'get', () => deps.db!.get({ collection, id }));
    if (!result.ok) return result;
    if (result.value === null) return err({ error: createApiError({ code: 'NOT_FOUND', message: 'record not found' }) });
    return ok({ value: { record: result.value } });
  }
});

export const connectorsDbUpdateRoute = defineJsonRoute<DbUpdateRequest, ConnectorsDbRecordResponse, ConnectorsHttpDeps>({
  method: 'patch', path: '/api/connectors/db/:collection/:id', parse: parseDbUpdate, handle: async ({ input: { collection, id, patch }, deps }) => {
    if (!deps.db) return err({ error: notConfiguredError('db') });
    const result = await guardedCall(deps, 'db', 'update', () => deps.db!.update({ collection, id, patch }));
    if (!result.ok) return result;
    if (result.value === null) return err({ error: createApiError({ code: 'NOT_FOUND', message: 'record not found' }) });
    return ok({ value: { record: result.value } });
  }
}, { requireSameOrigin: true });

export const connectorsDbDeleteRoute = defineJsonRoute<DbCollectionIdParams, ConnectorsOkResponse, ConnectorsHttpDeps>({
  method: 'delete', path: '/api/connectors/db/:collection/:id', parse: parseDbCollectionId, handle: async ({ input: { collection, id }, deps }) => {
    if (!deps.db) return err({ error: notConfiguredError('db') });
    const result = await guardedCall(deps, 'db', 'delete', () => deps.db!.delete({ collection, id }));
    return result.ok ? ok({ value: { ok: true } }) : result;
  }
}, { requireSameOrigin: true });

export const connectorsDbQueryRoute = defineJsonRoute<DbQueryRequest, ConnectorsDbQueryResponse, ConnectorsHttpDeps>({
  method: 'get', path: '/api/connectors/db/:collection', parse: parseDbQueryRequest, handle: async ({ input: { collection, query }, deps }) => {
    if (!deps.db) return err({ error: notConfiguredError('db') });
    const result = await guardedCall(deps, 'db', 'query', () => deps.db!.query({ collection }, query));
    return result.ok ? ok({ value: { records: result.value } }) : result;
  }
});

// ---------------------------------------------------------------------------
// realtime
// ---------------------------------------------------------------------------
//
// `RealtimeProvider.subscribe` deliberately has no route here: a request/response JSON route has
// no way to keep a subscription alive to push future events back to the caller — that's inherently
// a streaming/websocket concern (matching this package's own `sse.ts`/`raw-sse.ts` machinery for
// *other* long-lived channels), out of scope for this route pack. `publish` is the one
// realtime operation that fits the request/response shape every other route in this file already
// uses.

interface RealtimePublishRequest {
  readonly channel: string;
  readonly event: unknown;
}

function parseRealtimePublish(input: RouteInputContext): Result<RealtimePublishRequest> {
  const channel = input.params.channel;
  if (typeof channel !== 'string' || channel.length === 0) {
    return err({ error: validationError({ message: 'channel must be a non-empty path parameter' }) });
  }
  if (!isRecord(input.body) || !('event' in input.body)) {
    return err({ error: validationError({ message: 'body must be a JSON object with an event field' }, { issues: [{ path: 'event', message: 'required' }] }) });
  }
  return ok({ value: { channel, event: input.body.event } });
}

export const connectorsRealtimePublishRoute = defineJsonRoute<RealtimePublishRequest, ConnectorsOkResponse, ConnectorsHttpDeps>({
  method: 'post', path: '/api/connectors/realtime/:channel/publish', parse: parseRealtimePublish, handle: async ({ input: { channel, event }, deps }) => {
    if (!deps.realtime) return err({ error: notConfiguredError('realtime') });
    const result = await guardedCall(deps, 'realtime', 'publish', () => deps.realtime!.publish({ channel, event }));
    return result.ok ? ok({ value: { ok: true } }) : result;
  }
}, { requireSameOrigin: true });

/** Mounts every connectors route on `app`. A pack's `http(app, services)` calls this directly. */
export function registerConnectorsRoutes({ app, deps, adapter }: { readonly app: Express; readonly deps: ConnectorsHttpDeps; readonly adapter: AdapterContext }, _optional: Record<string, never> = {}): void {
  mountJsonRoute({ app, spec: connectorsAuthSignUpRoute, deps, adapter });
  mountJsonRoute({ app, spec: connectorsAuthSignInRoute, deps, adapter });
  mountJsonRoute({ app, spec: connectorsAuthSignOutRoute, deps, adapter });
  mountJsonRoute({ app, spec: connectorsAuthSessionRoute, deps, adapter });

  mountJsonRoute({ app, spec: connectorsStoragePutRoute, deps, adapter });
  mountJsonRoute({ app, spec: connectorsStorageGetRoute, deps, adapter });
  mountJsonRoute({ app, spec: connectorsStorageDeleteRoute, deps, adapter });
  mountJsonRoute({ app, spec: connectorsStorageListRoute, deps, adapter });

  mountJsonRoute({ app, spec: connectorsPaymentsChargeRoute, deps, adapter });
  mountJsonRoute({ app, spec: connectorsPaymentsGetRoute, deps, adapter });
  mountJsonRoute({ app, spec: connectorsPaymentsRefundRoute, deps, adapter });

  mountJsonRoute({ app, spec: connectorsDbInsertRoute, deps, adapter });
  mountJsonRoute({ app, spec: connectorsDbGetRoute, deps, adapter });
  mountJsonRoute({ app, spec: connectorsDbUpdateRoute, deps, adapter });
  mountJsonRoute({ app, spec: connectorsDbDeleteRoute, deps, adapter });
  mountJsonRoute({ app, spec: connectorsDbQueryRoute, deps, adapter });

  mountJsonRoute({ app, spec: connectorsRealtimePublishRoute, deps, adapter });
}
