import { expect, it, vi } from 'vitest';
import { createAgentPluginsController } from '../controllers/agent-plugins.controller.js';
import { createAgentPluginFilesController } from '../controllers/agent-plugin-files.controller.js';
import { createMemoryAgentPluginsApi } from '../adapters/memory.js';
import { runAgentPluginsApiConformance } from '../conformance/agent-plugins-api.conformance.js';
import type { AgentPluginSummary, AgentPluginFiles } from '../models.js';

export const alpha: AgentPluginSummary = { pluginId: 'ui-ux-design', version: '1', description: 'Design interfaces', keywords: ['UI'], enabled: false, skills: [{ name: 'design', summary: 'A design skill' }], mcpServerIds: ['design-api'] };
export const beta: AgentPluginSummary = { ...alpha, pluginId: 'second', enabled: true };
export const files: AgentPluginFiles = { pluginId: alpha.pluginId, files: [{ relativePath: 'skills/design/SKILL.md', sizeBytes: 8, content: '# Design', omitted: null }, { relativePath: 'plugin.json', sizeBytes: 2, content: '{}', omitted: null }], truncated: true, limits: { maxFiles: 200, maxEntries: 1000, maxFileBytes: 65536, maxTotalBytes: 1048576 } };
const grants = ['admin.plugins.read', 'admin.plugins.enable'];
function setup(permissions = grants) { const api = createMemoryAgentPluginsApi({ plugins: [alpha, beta], files: { [alpha.pluginId]: files } }); return { api, c: createAgentPluginsController({ api, permissions }) }; }
it('runs the adapter contract against memory', async () => { const results = await runAgentPluginsApiConformance({ create: () => createMemoryAgentPluginsApi({ plugins: [alpha, beta], files: { [alpha.pluginId]: files } }), pluginId: alpha.pluginId, otherPluginId: beta.pluginId }); expect(results.filter(r => !r.passed)).toEqual([]); expect(results.length).toBeGreaterThanOrEqual(10); });
it('denies reads by default and denies mutations with only read permission', async () => { const { api } = setup(); const read = vi.spyOn(api, 'list'), write = vi.spyOn(api, 'setEnabled'); const denied = createAgentPluginsController({ api }); await denied.load({}); expect(read).not.toHaveBeenCalled(); const c = createAgentPluginsController({ api, permissions: ['admin.plugins.read'] }); await c.load({}); expect(await c.setEnabled({ pluginId: alpha.pluginId, enabled: true })).toBe(false); c.requestDisable({ pluginId: beta.pluginId, variant: 'disable' }); expect(c.getSnapshot().pendingDisable).toBeNull(); expect(write).not.toHaveBeenCalled(); });
it('replaces one row with server truth without a second GET', async () => { const { api, c } = setup(); const list = vi.spyOn(api, 'list'); await c.load({}); const before = c.getSnapshot().plugins![0]!; await c.setEnabled({ pluginId: alpha.pluginId, enabled: true }); expect(c.getSnapshot().plugins![0]!.enabled).toBe(true); expect(before.enabled).toBe(false); expect(list).toHaveBeenCalledTimes(1); });
it('keeps the old state and list on refusal and does not echo server errors', async () => { const { api, c } = setup(); await c.load({}); vi.spyOn(api, 'setEnabled').mockRejectedValue(new Error('private credential')); expect(await c.setEnabled({ pluginId: alpha.pluginId, enabled: true })).toBe(false); expect(c.getSnapshot().plugins![0]!.enabled).toBe(false); expect(c.getSnapshot().error).toBeNull(); expect(c.getSnapshot().actionError).toBe('Failed to update agent plugin'); });
it('requires a fresh confirmation and does not accidentally enable an externally disabled row', async () => { const { api, c } = setup(); await c.load({}); c.requestDisable({ pluginId: beta.pluginId, variant: 'remove' }); expect(c.getSnapshot().pendingDisable).toEqual({ pluginId: beta.pluginId, variant: 'remove' }); await api.setEnabled({ pluginId: beta.pluginId, enabled: false }); await c.load({}); const write = vi.spyOn(api, 'setEnabled'); expect(await c.confirmDisable({})).toBe(false); expect(write).not.toHaveBeenCalled(); expect(c.getSnapshot().pendingDisable).toBeNull(); });
it('keeps independent row writes when replies settle out of order and blocks duplicate clicks', async () => { const { api, c } = setup(); await c.load({}); const original = api.setEnabled; let first!: () => void, second!: () => void; const write = vi.spyOn(api, 'setEnabled').mockImplementation(async (input, options) => { await new Promise<void>(resolve => { if (input.pluginId === alpha.pluginId) first = resolve; else second = resolve; }); return original(input, options); }); const a = c.setEnabled({ pluginId: alpha.pluginId, enabled: true }); const b = c.setEnabled({ pluginId: beta.pluginId, enabled: false }); expect(c.getSnapshot().plugins!.map(p => p.enabled)).toEqual([false, true]); expect(await c.setEnabled({ pluginId: alpha.pluginId, enabled: true })).toBe(false); second(); await b; first(); await a; expect(c.getSnapshot().plugins!.map(p => p.enabled)).toEqual([true, false]); expect(write).toHaveBeenCalledTimes(2); expect(c.getSnapshot().busyIds).toEqual([]); });
it('does not let an older list overwrite an accepted activation', async () => { const { api, c } = setup(); await c.load({}); let resolve!: (rows: readonly AgentPluginSummary[]) => void; vi.spyOn(api, 'list').mockImplementationOnce(() => new Promise(r => { resolve = r; })); const load = c.load({}); await c.setEnabled({ pluginId: alpha.pluginId, enabled: true }); resolve([alpha, beta]); await load; expect(c.getSnapshot().plugins![0]!.enabled).toBe(true); expect(c.getSnapshot().loading).toBe(false); });
it('aborts on disposal and ignores late settlement', async () => { const { api, c } = setup(); await c.load({}); let resolve!: (row: AgentPluginSummary) => void; let signal: AbortSignal | undefined; vi.spyOn(api, 'setEnabled').mockImplementation((_input, options) => { signal = options?.signal; return new Promise(r => { resolve = r; }); }); const write = c.setEnabled({ pluginId: alpha.pluginId, enabled: true }); c.dispose({}); const state = c.getSnapshot(); expect(signal!.aborted).toBe(true); resolve({ ...alpha, enabled: true }); expect(await write).toBe(false); expect(c.getSnapshot()).toBe(state); });
it('selects the tree top file and ignores stale inspector reads after switching or closing', async () => { const { api } = setup(); const c = createAgentPluginFilesController({ api, permissions: grants }); await c.open({ pluginId: alpha.pluginId }); expect(c.getSnapshot().selectedPath).toBe('plugin.json'); c.select({ path: 'missing' }); expect(c.getSnapshot().selectedPath).toBe('plugin.json'); c.select({ path: 'skills/design/SKILL.md' }); expect(c.getSnapshot().selectedPath).toBe('skills/design/SKILL.md'); let resolve!: (listing: AgentPluginFiles) => void; vi.spyOn(api, 'files').mockImplementationOnce(() => new Promise(r => { resolve = r; })); const pending = c.open({ pluginId: beta.pluginId }); expect(c.getSnapshot().listing).toBeNull(); c.close({}); resolve({ ...files, pluginId: beta.pluginId }); await pending; expect(c.getSnapshot().pluginId).toBeNull(); expect(c.getSnapshot().listing).toBeNull(); });
it('denies inspector reads without grants and reports file failures safely', async () => { const { api } = setup(); const read = vi.spyOn(api, 'files'); const denied = createAgentPluginFilesController({ api }); await denied.open({ pluginId: alpha.pluginId }); expect(read).not.toHaveBeenCalled(); const c = createAgentPluginFilesController({ api, permissions: ['admin.plugins.read'] }); read.mockRejectedValue(new Error('raw secret')); await c.open({ pluginId: beta.pluginId }); expect(c.getSnapshot().error).toBe('Failed to load package files'); expect(c.getSnapshot().listing).toBeNull(); expect(c.getSnapshot().loading).toBe(false); });
