/** Contract semver is independent of the npm package version. Only implemented entries may be required. */
export const KIT_CONTRACT = { id: '@jini-ai/ui-kit', version: '1.0.0' } as const;
export interface KitComponentSpec {
  readonly status: 'implemented' | 'planned'; readonly tier: 'control' | 'composite' | 'layout';
  readonly since: string | null; readonly parts: readonly string[]; readonly focusTarget: string;
  readonly portal: 'none' | 'overlay'; readonly safety: boolean; readonly behaviors: readonly string[];
  readonly props: readonly string[]; readonly events: readonly string[]; readonly variants: readonly string[]; readonly states: readonly string[];
}
export const kitSpec = {
  Button: {"status": "implemented", "tier": "control", "since": "1.0.0", "parts": ["kit.button"], "focusTarget": "button", "portal": "none", "safety": false, "behaviors": ["press", "disabled-blocks-press", "attrs-on-focus-target"], "props": ["attrs", "className", "children", "disabled", "pending", "variant", "type", "ref", "onPress"], "events": ["onPress"], "variants": ["primary", "secondary", "danger", "warning", "ghost"], "states": ["disabled", "pending"]},
  IconButton: {"status": "implemented", "tier": "control", "since": "1.0.0", "parts": ["kit.icon-button"], "focusTarget": "button", "portal": "none", "safety": false, "behaviors": ["accessible-label", "press", "attrs-on-focus-target"], "props": ["attrs", "className", "children", "disabled", "pending", "variant", "type", "ref", "onPress", "label"], "events": ["onPress"], "variants": ["primary", "secondary", "danger", "warning", "ghost"], "states": ["disabled", "pending"]},
  TextField: {"status": "implemented", "tier": "control", "since": "1.0.0", "parts": ["kit.text-field", "kit.field-label"], "focusTarget": "input", "portal": "none", "safety": false, "behaviors": ["value-change", "labelled-control", "attrs-on-focus-target"], "props": ["attrs", "className", "label", "value", "disabled", "required", "placeholder", "type", "ref", "onValueChange"], "events": ["onValueChange"], "variants": [], "states": ["disabled"]},
  TextArea: {"status": "implemented", "tier": "control", "since": "1.0.0", "parts": ["kit.text-area", "kit.field-label"], "focusTarget": "textarea", "portal": "none", "safety": false, "behaviors": ["value-change", "labelled-control", "attrs-on-focus-target"], "props": ["attrs", "className", "label", "value", "disabled", "required", "placeholder", "ref", "onValueChange", "rows"], "events": ["onValueChange"], "variants": [], "states": ["disabled"]},
  Select: {"status": "implemented", "tier": "control", "since": "1.0.0", "parts": ["kit.select", "kit.field-label"], "focusTarget": "select", "portal": "none", "safety": false, "behaviors": ["native-select", "value-change", "attrs-on-focus-target"], "props": ["attrs", "className", "label", "value", "disabled", "required", "ref", "onValueChange", "options"], "events": ["onValueChange"], "variants": [], "states": ["disabled"]},
  Checkbox: {"status": "implemented", "tier": "control", "since": "1.0.0", "parts": ["kit.checkbox"], "focusTarget": "input", "portal": "none", "safety": false, "behaviors": ["checked-change", "labelled-control", "attrs-on-focus-target"], "props": ["attrs", "className", "label", "checked", "disabled", "ref", "onCheckedChange"], "events": ["onCheckedChange"], "variants": [], "states": ["disabled"]},
  Switch: {"status": "implemented", "tier": "control", "since": "1.0.0", "parts": ["kit.switch"], "focusTarget": "input", "portal": "none", "safety": false, "behaviors": ["checked-change", "switch-role", "attrs-on-focus-target"], "props": ["attrs", "className", "label", "checked", "disabled", "ref", "onCheckedChange"], "events": ["onCheckedChange"], "variants": [], "states": ["disabled"]},
  Dialog: {"status": "implemented", "tier": "composite", "since": "1.0.0", "parts": ["kit.dialog", "kit.dialog-title", "kit.dialog-close", "kit.overlay"], "focusTarget": "dialog", "portal": "overlay", "safety": false, "behaviors": ["escape-dismissal", "pending-blocks-dismissal", "focus-restore"], "props": ["attrs", "className", "open", "title", "children", "pending", "closeLabel", "ref", "onClose"], "events": ["onClose"], "variants": [], "states": ["disabled", "pending"]},
  ConfirmDialog: {"status": "implemented", "tier": "composite", "since": "1.0.0", "parts": ["confirm.dialog", "confirm.title", "confirm.body", "confirm.actions", "confirm.cancel", "confirm.confirm"], "focusTarget": "cancel", "portal": "overlay", "safety": true, "behaviors": ["pending-blocks-every-dismissal", "cancel-first-focus", "agent-confirm-withheld", "consequence-label"], "props": ["attrs", "className", "open", "title", "body", "confirmLabel", "cancelLabel", "tone", "pending", "consequence", "agentHandle", "agentMayConfirm", "errorLabel", "actionAccessibleNames", "onConfirm", "onCancel"], "events": ["onConfirm", "onCancel"], "variants": ["default", "warning", "danger"], "states": ["disabled", "pending"]},
  Tabs: {"status": "implemented", "tier": "composite", "since": "1.0.0", "parts": ["kit.tabs", "kit.tab", "kit.tab-panel"], "focusTarget": "active-tab", "portal": "none", "safety": false, "behaviors": ["roving-tabs", "labelled-panel"], "props": ["attrs", "className", "label", "value", "items", "onValueChange"], "events": ["onValueChange"], "variants": [], "states": []},
  Menu: {"status": "implemented", "tier": "composite", "since": "1.0.0", "parts": ["kit.menu-trigger", "kit.menu", "kit.menu-item"], "focusTarget": "trigger-and-item", "portal": "none", "safety": false, "behaviors": ["roving-menu", "escape-dismissal", "focus-restore"], "props": ["attrs", "className", "label", "items", "disabled"], "events": [], "variants": [], "states": ["open"]},
  Toast: {"status": "implemented", "tier": "composite", "since": "1.0.0", "parts": ["kit.toast", "kit.toast-dismiss", "kit.toast-region"], "focusTarget": "dismiss", "portal": "overlay", "safety": false, "behaviors": ["live-region", "dismiss-toast"], "props": ["attrs", "className", "message", "tone", "dismissLabel", "onDismiss"], "events": ["onDismiss"], "variants": ["info", "success", "warning", "danger"], "states": []},
  Tooltip: {"status": "implemented", "tier": "composite", "since": "1.0.0", "parts": ["kit.tooltip-trigger", "kit.tooltip"], "focusTarget": "trigger", "portal": "none", "safety": false, "behaviors": ["focus-tooltip", "hover-tooltip", "escape-dismissal"], "props": ["attrs", "className", "content", "children", "label"], "events": [], "variants": [], "states": ["open"]},
  Notice: {"status": "implemented", "tier": "control", "since": "1.0.0", "parts": ["kit.notice"], "focusTarget": "root", "portal": "none", "safety": false, "behaviors": ["status-region"], "props": ["attrs", "className", "children", "tone"], "events": [], "variants": ["info", "success", "warning", "danger"], "states": []},
  Spinner: {"status": "implemented", "tier": "control", "since": "1.0.0", "parts": ["kit.spinner"], "focusTarget": "root", "portal": "none", "safety": false, "behaviors": ["accessible-label"], "props": ["attrs", "className", "label"], "events": [], "variants": [], "states": []},
  Badge: {"status": "implemented", "tier": "control", "since": "1.0.0", "parts": ["kit.badge"], "focusTarget": "root", "portal": "none", "safety": false, "behaviors": ["text-content"], "props": ["attrs", "className", "children", "tone"], "events": [], "variants": ["info", "success", "warning", "danger"], "states": []},
  Link: {"status": "planned", "tier": "composite", "since": null, "parts": [], "focusTarget": "planned", "portal": "none", "safety": false, "behaviors": [], "props": [], "events": [], "variants": [], "states": []},
  Icon: {"status": "planned", "tier": "composite", "since": null, "parts": [], "focusTarget": "planned", "portal": "none", "safety": false, "behaviors": [], "props": [], "events": [], "variants": [], "states": []},
  RadioGroup: {"status": "planned", "tier": "composite", "since": null, "parts": [], "focusTarget": "planned", "portal": "none", "safety": false, "behaviors": [], "props": [], "events": [], "variants": [], "states": []},
  Field: {"status": "planned", "tier": "composite", "since": null, "parts": [], "focusTarget": "planned", "portal": "none", "safety": false, "behaviors": [], "props": [], "events": [], "variants": [], "states": []},
  Card: {"status": "planned", "tier": "composite", "since": null, "parts": [], "focusTarget": "planned", "portal": "none", "safety": false, "behaviors": [], "props": [], "events": [], "variants": [], "states": []},
  Table: {"status": "planned", "tier": "composite", "since": null, "parts": [], "focusTarget": "planned", "portal": "none", "safety": false, "behaviors": [], "props": [], "events": [], "variants": [], "states": []},
  Popover: {"status": "planned", "tier": "composite", "since": null, "parts": [], "focusTarget": "planned", "portal": "none", "safety": false, "behaviors": [], "props": [], "events": [], "variants": [], "states": []},
  Combobox: {"status": "planned", "tier": "composite", "since": null, "parts": [], "focusTarget": "planned", "portal": "none", "safety": false, "behaviors": [], "props": [], "events": [], "variants": [], "states": []},
  Stack: {"status": "planned", "tier": "layout", "since": null, "parts": [], "focusTarget": "planned", "portal": "none", "safety": false, "behaviors": [], "props": [], "events": [], "variants": [], "states": []},
  Grid: {"status": "planned", "tier": "layout", "since": null, "parts": [], "focusTarget": "planned", "portal": "none", "safety": false, "behaviors": [], "props": [], "events": [], "variants": [], "states": []},
  ShellLayout: {"status": "planned", "tier": "layout", "since": null, "parts": [], "focusTarget": "planned", "portal": "none", "safety": false, "behaviors": [], "props": [], "events": [], "variants": [], "states": []},
  Sidebar: {"status": "planned", "tier": "layout", "since": null, "parts": [], "focusTarget": "planned", "portal": "none", "safety": false, "behaviors": [], "props": [], "events": [], "variants": [], "states": []},
  NavItem: {"status": "planned", "tier": "layout", "since": null, "parts": [], "focusTarget": "planned", "portal": "none", "safety": false, "behaviors": [], "props": [], "events": [], "variants": [], "states": []},
  PageHeader: {"status": "planned", "tier": "layout", "since": null, "parts": [], "focusTarget": "planned", "portal": "none", "safety": false, "behaviors": [], "props": [], "events": [], "variants": [], "states": []},
  Section: {"status": "planned", "tier": "layout", "since": null, "parts": [], "focusTarget": "planned", "portal": "none", "safety": false, "behaviors": [], "props": [], "events": [], "variants": [], "states": []},
  EmptyState: {"status": "planned", "tier": "layout", "since": null, "parts": [], "focusTarget": "planned", "portal": "none", "safety": false, "behaviors": [], "props": [], "events": [], "variants": [], "states": []},
  OverlayHost: {"status": "planned", "tier": "layout", "since": null, "parts": [], "focusTarget": "planned", "portal": "none", "safety": false, "behaviors": [], "props": [], "events": [], "variants": [], "states": []},
} as const satisfies Record<string, KitComponentSpec>;
export type KitComponentName = keyof typeof kitSpec;
export type ImplementedComponentName = { [K in KitComponentName]: typeof kitSpec[K]['status'] extends 'implemented' ? K : never }[KitComponentName];
export type KitPart = typeof kitSpec[ImplementedComponentName]['parts'][number];
export const implementedComponents = Object.freeze(Object.keys(kitSpec).filter(
  (name): name is ImplementedComponentName => kitSpec[name as KitComponentName].status === 'implemented',
));
export const kitParts: readonly KitPart[] = Object.freeze([...new Set(implementedComponents.flatMap(name => [...kitSpec[name].parts]))]);
