import { forwardRef, StrictMode, Suspense } from 'react';
import { afterEach, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { createKit, KitProvider, type ButtonProps } from '@jini-ai/ui-kit/react';
import { createAdmin } from '../../../core/module/index.js';
import { agentPlugins } from '../index.js';
import { createMemoryAgentPluginsApi } from '../../adapters/memory.js';
import type { AgentPluginFiles, AgentPluginSummary } from '../../models.js';
afterEach(cleanup);
const alpha: AgentPluginSummary = { pluginId: 'ui-ux-design', version: null, description: 'Design interfaces', keywords: ['UI'], enabled: false, skills: [{ name: 'design', summary: 'A design skill' }], mcpServerIds: ['design-api'] };
const beta: AgentPluginSummary = { ...alpha, pluginId: 'second', description: null, skills: [], mcpServerIds: [], keywords: [], enabled: true };
const listing: AgentPluginFiles = { pluginId: alpha.pluginId, files: [{ relativePath: 'skills/design/SKILL.md', sizeBytes: 8, content: '# Design', omitted: null }, { relativePath: 'plugin.json', sizeBytes: 2, content: '{}', omitted: null }, { relativePath: 'binary.dat', sizeBytes: 3, content: null, omitted: 'binary' }], truncated: true, limits: { maxFiles: 200, maxEntries: 2000, maxFileBytes: 524288, maxTotalBytes: 4194304 } };
const grants = ['admin.plugins.read', 'admin.plugins.enable'];
function setup(permissions: readonly string[] = [], requestedTab?: string) {
  const feature = agentPlugins({}, { uninstallNotice: 'Packages are managed by this host.' }), api = createMemoryAgentPluginsApi({ plugins: [alpha, beta], files: { [alpha.pluginId]: listing } });
  const admin = createAdmin({ modules: [feature], ports: { agentPluginsApi: api } }, { permissions }); const { Page, tabs } = feature.react.pages.agentPlugins;
  const tree = () => <StrictMode><feature.react.Provider admin={admin}><Suspense fallback="Loading"><Page tabs={tabs} description={admin.describe().pages[0]!} {...(requestedTab ? { requestedTab } : {})} /></Suspense></feature.react.Provider></StrictMode>;
  return { api, admin, tree };
}
it('denies default mounts without reading the backend', async () => { const { api, tree } = setup(); const list = vi.spyOn(api, 'list'); render(tree()); expect(await screen.findByText('Permission denied')).toBeVisible(); expect(list).not.toHaveBeenCalled(); expect(screen.queryByRole('tab')).toBeNull(); });
it('renders both enabled and disabled rows read-only with details and inspection', async () => { const { api, tree } = setup(['admin.plugins.read'], 'unknown'); const write = vi.spyOn(api, 'setEnabled'); render(tree()); expect(await screen.findByRole('switch', { name: 'Enable UI UX Design' })).toBeDisabled(); expect(screen.getByRole('switch', { name: 'Disable Second' })).toBeChecked(); expect(screen.getByRole('switch', { name: 'Disable Second' })).toBeDisabled(); fireEvent.click(screen.getByRole('button', { name: 'Expand UI UX Design' })); expect(screen.getByRole('region', { name: 'Portable components' })).toBeVisible(); expect(screen.getByText('A design skill')).toBeVisible(); expect(screen.getByRole('button', { name: 'Uninstall UI UX Design — unavailable' })).toBeDisabled(); expect(screen.getByText('Packages are managed by this host.')).toBeVisible(); expect(write).not.toHaveBeenCalled(); });
it('preserves all rows across lazy list tabs and shows an honest marketplace', async () => { const { api, tree } = setup(grants); const list = vi.spyOn(api, 'list'); render(tree()); await screen.findByRole('switch', { name: 'Enable UI UX Design' }); const baseline = list.mock.calls.length; fireEvent.click(screen.getByRole('tab', { name: 'Downloaded' })); expect(await screen.findByRole('button', { name: 'Turn off Second' })).toBeVisible(); expect(screen.getByRole('button', { name: 'Enable UI UX Design' })).toBeVisible(); fireEvent.click(screen.getByRole('tab', { name: 'Marketplace' })); expect(await screen.findByText('Nothing to browse yet')).toBeVisible(); expect(screen.getByRole('link', { name: 'Read the package format' })).toHaveAttribute('href', 'https://agent-plugins.org/specification'); expect(screen.queryByRole('button', { name: /install/i })).toBeNull(); fireEvent.click(screen.getByRole('tab', { name: 'Installed' })); await screen.findByRole('switch', { name: 'Enable UI UX Design' }); expect(list).toHaveBeenCalledTimes(baseline); });
it('uses direct enable, guarded disable and cancel-first focus without optimistic activation', async () => { const { api, tree } = setup(grants); const original = api.setEnabled; let settle!: () => void; const write = vi.spyOn(api, 'setEnabled'); render(tree()); const control = await screen.findByRole('switch', { name: 'Enable UI UX Design' }); fireEvent.click(control); await waitFor(() => expect(screen.getByRole('switch', { name: 'Disable UI UX Design' })).toBeChecked()); expect(write).toHaveBeenCalledWith({ pluginId: alpha.pluginId, enabled: true }, expect.objectContaining({ signal: expect.any(AbortSignal) })); write.mockClear(); fireEvent.click(screen.getByRole('switch', { name: 'Disable UI UX Design' })); const dialog = await screen.findByRole('alertdialog'); expect(write).not.toHaveBeenCalled(); expect(within(dialog).getByRole('button', { name: /Cancel/ })).toHaveFocus(); fireEvent.click(within(dialog).getByRole('button', { name: /Cancel/ })); expect(screen.queryByRole('alertdialog')).toBeNull();
  write.mockImplementation(async (input, options) => { await new Promise<void>(resolve => { settle = resolve; }); return original(input, options); }); fireEvent.click(screen.getByRole('switch', { name: 'Disable UI UX Design' })); fireEvent.click(within(await screen.findByRole('alertdialog')).getByRole('button', { name: /^Disable/ })); await waitFor(() => expect(write).toHaveBeenCalledTimes(1)); expect(screen.getByRole('switch', { name: 'Disable UI UX Design' })).toBeChecked(); expect(screen.getByRole('switch', { name: 'Disable UI UX Design' })).toBeDisabled(); expect(within(screen.getByRole('alertdialog')).getByRole('button', { name: /Cancel/ })).toBeDisabled(); settle(); await waitFor(() => expect(screen.queryByRole('alertdialog')).toBeNull()); expect(screen.getByRole('switch', { name: 'Enable UI UX Design' })).not.toBeChecked(); });
it('Downloaded Turn off confirms a disable without deleting or hiding the package', async () => { const { api, tree } = setup(grants); const write = vi.spyOn(api, 'setEnabled'); render(tree()); await screen.findByRole('switch', { name: 'Disable Second' }); fireEvent.click(screen.getByRole('tab', { name: 'Downloaded' })); fireEvent.click(await screen.findByRole('button', { name: 'Turn off Second' })); const dialog = await screen.findByRole('alertdialog'); expect(within(dialog).getByText(/remains listed on both tabs/)).toBeVisible(); fireEvent.click(within(dialog).getByRole('button', { name: /^Turn off/ })); await screen.findByRole('button', { name: 'Enable Second' }); expect(write).toHaveBeenCalledWith({ pluginId: beta.pluginId, enabled: false }, expect.anything()); });
it('inspects disabled packages with file omissions, caps, keyboard navigation and per-file wrap reset', async () => { const { tree } = setup(['admin.plugins.read']); render(tree()); fireEvent.click(await screen.findByRole('button', { name: 'Inspect UI UX Design package files' })); const dialog = await screen.findByRole('dialog', { name: 'UI UX Design — Package files' }); await within(dialog).findByText('Binary file — not shown.'); expect(within(dialog).queryByRole('button', { name: /Wrap:/ })).toBeNull(); expect(within(dialog).getByRole('note')).toHaveTextContent('Some files are not listed'); const binary = within(dialog).getByRole('treeitem', { name: 'binary.dat' }); expect(binary).toHaveAttribute('aria-selected', 'true'); const fileTree = within(dialog).getByRole('tree'); fireEvent.keyDown(fileTree, { key: 'ArrowDown' }); const json = within(dialog).getByRole('treeitem', { name: 'plugin.json' }); await waitFor(() => expect(json).toHaveFocus()); fireEvent.keyDown(fileTree, { key: 'Enter' }); expect(await within(dialog).findByRole('button', { name: 'Wrap: on' })).toHaveAttribute('aria-pressed', 'true'); fireEvent.click(within(dialog).getByRole('button', { name: 'Wrap: on' })); expect(within(dialog).getByRole('button', { name: 'Wrap: off' })).toHaveAttribute('aria-pressed', 'false'); fireEvent.keyDown(fileTree, { key: 'ArrowDown' }); fireEvent.keyDown(fileTree, { key: 'ArrowRight' }); expect(within(dialog).getByRole('treeitem', { name: 'skills' })).toHaveAttribute('aria-expanded', 'true'); fireEvent.keyDown(fileTree, { key: 'ArrowRight' }); fireEvent.keyDown(fileTree, { key: 'ArrowRight' }); fireEvent.keyDown(fileTree, { key: 'ArrowRight' }); fireEvent.keyDown(fileTree, { key: 'Enter' }); expect(await within(dialog).findByText('# Design')).toBeVisible(); expect(within(dialog).getByRole('button', { name: 'Wrap: on' })).toHaveAttribute('aria-pressed', 'true'); fireEvent.click(within(dialog).getByRole('button', { name: 'Close package files' })); expect(screen.queryByRole('dialog')).toBeNull(); });
it('honors host Button overrides for page and confirmation actions', async () => {
  const CustomButton = forwardRef<HTMLButtonElement, ButtonProps>((props, ref) => <button ref={ref} {...props.attrs} data-custom-button="yes" type={props.type ?? 'button'} disabled={props.disabled || props.pending} onClick={() => props.onPress?.({})}>{props.children}</button>);
  const kit = createKit({ components: { Button: CustomButton } }); const { tree } = setup(grants); render(<KitProvider kit={kit}>{tree()}</KitProvider>); await screen.findByRole('switch', { name: 'Disable Second' }); expect(screen.getByRole('button', { name: 'Reload packages' })).toHaveAttribute('data-custom-button', 'yes'); fireEvent.click(screen.getByRole('switch', { name: 'Disable Second' })); const dialog = await screen.findByRole('alertdialog'); expect(within(dialog).getByRole('button', { name: /Cancel/ })).toHaveAttribute('data-custom-button', 'yes'); expect(within(dialog).getByRole('button', { name: /^Disable/ })).toHaveAttribute('data-custom-button', 'yes');
});
