/**
 * Compatibility entry for the agent executor's original module path.
 * The split implementation owns subprocess launch, credential delivery,
 * cancellation, and run events. Named re-exports preserve the existing API
 * and AgentExecutorError identity across this entry and the package barrel;
 * wrappers or a second implementation would let tested and shipped behavior drift.
 * See agent-executor/index.ts for the driver contracts and invariants.
 */

export {
  type SupportedStreamFormat,
  isSupportedStreamFormat,
  type AgentExecutorCompatibility,
  assessAgentExecutorCompatibility,
  isAgentExecutorSupported,
  type AgentRuntimeEventTranslation,
  extractUsageTokens,
  translateStatusEvent,
  translateToolResultEvent,
  translateErrorEvent,
  translateTurnEndEvent,
  translateAgentRuntimeEvent,
  type AgentExecutorErrorCode,
  AgentExecutorError,
  type AgentExecutorRunInput,
  type AgentExecutor,
  type UserMessageDelivery,
  type CollectProcessTreePidsPort,
  type StopProcessesPort,
  type AgentCleanupFailurePhase,
  type AgentCleanupFailureContext,
  type ContinuationOptions,
  type McpJsonInjectionOptions,
  MCP_BRIDGE_UNAVAILABLE,
  unavailableJiniBridgeStatus,
  buildMcpJsonServerEntry,
  mergeMcpJsonContent,
  buildAcpMcpBridgeServers,
  mergeEnvContentMcpConfig,
  mergeEnvContentInstructions,
  buildCodexMcpServerToml,
  buildCodexHomeConfigToml,
  resolveSourceCodexHomeDir,
  type McpBridgeDelivery,
  buildMcpBridgeDelivery,
  type PreparedCodexHome,
  type PreparedClaudeConfigDir,
  type ClaudeConfigDirSeams,
  type ClaudeConfigDirIsolationOptions,
  resolveSourceClaudeConfigDir,
  type FailureClassificationContext,
  type ClassifyFailure,
  DEFAULT_BUFFERED_STDOUT_MAX_BYTES,
  applyAgentTranslationSideEffects,
  type CreateAgentExecutorOptions,
  resolveDefAndStreamFormat,
  resolveImageDeliveryAndArgvBudget,
  resolveRunEnv,
  resolveLaunch,
  stagePromptFile,
  stageLogFile,
  resolveMcpBridgeForRun,
  computeChildEnv,
  computeRuntimeContext,
  buildAgentBuildArgsOptions,
  type SystemPromptOverlayDelivery,
  resolveSystemPromptOverlayDelivery,
  buildRunArgs,
  writeMcpJsonIfNeeded,
  type PreparedSystemPromptOverlayFile,
  prepareSystemPromptOverlayFileIfNeeded,
  prepareCodexHomeIfNeeded,
  prepareClaudeConfigDirIfNeeded,
  guardWindowsCommandLineBudget,
  type SpawnAgentChildProcessResult,
  spawnAgentChildProcess,
  isStdinDrivenFormat,
  confirmChildSpawned,
  armHandoffWatcher,
  runAcpDispatch,
  runPiRpcDispatch,
  createAgentExecutor,
} from './agent-executor/index.js';
