import { nodeFilesystem } from './node-ports.js';

import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { test } from "vitest";
import { execFileSync } from "node:child_process";

import { assertCmdQuotable, buildNodeToolchainEnv, buildNodeToolchainShims as buildShims, writeNodeToolchain as writeToolchain } from "../node-toolchain/index.js";

const ELECTRON = "/Applications/Sample.app/Contents/MacOS/Sample";
const NPM_ROOT = "/Applications/Sample.app/Contents/Resources/npm";

function tempDir() {
  return fs.mkdtempSync(path.join(os.tmpdir(), "sample-desktop-node-toolchain-"));
}

test("buildNodeToolchainShims: POSIX node re-execs Electron itself, with ELECTRON_RUN_AS_NODE exported on its own line", () => {
  const shims = buildNodeToolchainShims({ electronPath: ELECTRON, npmRoot: NPM_ROOT, platform: "darwin" });
  assert.equal(
    shims.node,
    ["#!/bin/sh", "# Generated by Sample Desktop — rewritten on every launch. Do not edit.", "ELECTRON_RUN_AS_NODE=1", "export ELECTRON_RUN_AS_NODE", `exec '${ELECTRON}' "$@"`, ""].join(
      "\n",
    ),
  );
});

test("buildNodeToolchainShims: POSIX npm and npx re-exec Electron against the bundled npm's own CLI entry points", () => {
  const shims = buildNodeToolchainShims({ electronPath: ELECTRON, npmRoot: NPM_ROOT, platform: "linux" });
  const header = ["#!/bin/sh", "# Generated by Sample Desktop — rewritten on every launch. Do not edit.", "ELECTRON_RUN_AS_NODE=1", "export ELECTRON_RUN_AS_NODE"];
  assert.equal(shims.npm, [...header, `exec '${ELECTRON}' '${NPM_ROOT}/bin/npm-cli.js' "$@"`, ""].join("\n"));
  assert.equal(shims.npx, [...header, `exec '${ELECTRON}' '${NPM_ROOT}/bin/npx-cli.js' "$@"`, ""].join("\n"));
});

test("buildNodeToolchainShims: win32 writes .cmd variants with CRLF, @echo off, and set (not export)", () => {
  const shims = buildNodeToolchainShims({ electronPath: ELECTRON, npmRoot: NPM_ROOT, platform: "win32" });
  assert.equal(shims["node.cmd"], ["@echo off", "set ELECTRON_RUN_AS_NODE=1", `"${ELECTRON}" %*`, ""].join("\r\n"));
  assert.equal(shims["npm.cmd"], ["@echo off", "set ELECTRON_RUN_AS_NODE=1", `"${ELECTRON}" "${path.join(NPM_ROOT, "bin", "npm-cli.js")}" %*`, ""].join("\r\n"));
  assert.equal(shims["npx.cmd"], ["@echo off", "set ELECTRON_RUN_AS_NODE=1", `"${ELECTRON}" "${path.join(NPM_ROOT, "bin", "npx-cli.js")}" %*`, ""].join("\r\n"));

  assert.deepEqual(Object.keys(shims).sort(), ["node.cmd", "npm.cmd", "npx.cmd"]);
});

test("buildNodeToolchainShims: POSIX-only keys on a non-win32 platform", () => {
  const shims = buildNodeToolchainShims({ electronPath: ELECTRON, npmRoot: NPM_ROOT, platform: "darwin" });
  assert.deepEqual(Object.keys(shims).sort(), ["node", "npm", "npx"]);
});

test("buildNodeToolchainShims refuses a POSIX path containing a single quote, before writing anything", () => {
  assert.throws(() => buildNodeToolchainShims({ electronPath: "/Applications/Sam'ple.app/Sample", npmRoot: NPM_ROOT, platform: "darwin" }), /electronPath/);
  assert.throws(() => buildNodeToolchainShims({ electronPath: ELECTRON, npmRoot: "/Resources/np'm", platform: "darwin" }), /npmRoot/);
});

test("buildNodeToolchainShims refuses a win32 path containing % \" ^ or &", () => {
  for (const badChar of ["%", '"', "^", "&"]) {
    const dirty = `C:\\Program Files\\Sample ${badChar} evil\\Sample.exe`;
    assert.throws(() => buildNodeToolchainShims({ electronPath: dirty, npmRoot: NPM_ROOT, platform: "win32" }), /electronPath/, `char: ${badChar}`);
  }
});

test("assertCmdQuotable rejects empty/non-string input and every unsafe character, accepts a clean path", () => {
  assert.throws(() => assertCmdQuotable({ value: "", field: "field" }), /must be a non-empty string/);
  assert.throws(() => assertCmdQuotable({ value: undefined, field: "field" }), /must be a non-empty string/);
  for (const bad of ["a%b", 'a"b', "a^b", "a&b", "a\rb", "a\nb"]) {
    assert.throws(() => assertCmdQuotable({ value: bad, field: "field" }), /cannot be used/, `input: ${JSON.stringify(bad)}`);
  }
  assert.equal(assertCmdQuotable({ value: "C:\\Program Files\\Sample\\Sample.exe", field: "field" }), "C:\\Program Files\\Sample\\Sample.exe");
});

test("writeNodeToolchain writes exactly the three POSIX shims, mode 0o700, with no leftover temp files", () => {
  const userDataDir = tempDir();
  const paths = writeNodeToolchain({ userDataDir, electronPath: ELECTRON, npmRoot: NPM_ROOT, platform: "darwin" });
  assert.ok(paths, "a durable electronPath always writes the toolchain");

  assert.deepEqual(fs.readdirSync(paths.binDir).sort(), ["node", "npm", "npx"]);
  for (const name of ["node", "npm", "npx"]) {
    const mode: number = fs.statSync(path.join(paths.binDir, name)).mode & 0o777;
    assert.equal(mode, 0o700, `${name} mode`);
    const header = "#!/bin/sh\n# Generated by Sample Desktop — rewritten on every launch. Do not edit.\nELECTRON_RUN_AS_NODE=1\nexport ELECTRON_RUN_AS_NODE\n";
    const args = name === "node" ? "" : ` '${NPM_ROOT}/bin/${name}-cli.js'`;
    assert.equal(fs.readFileSync(path.join(paths.binDir, name), "utf8"), `${header}exec '${ELECTRON}'${args} "$@"\n`, `${name} bytes`);
  }


  assert.equal(fs.statSync(paths.binDir).mode & 0o777, 0o700, "bin dir mode");
  fs.chmodSync(paths.binDir, 0o777);
  writeNodeToolchain({ userDataDir, electronPath: ELECTRON, npmRoot: NPM_ROOT, platform: "darwin" });
  assert.equal(fs.statSync(paths.binDir).mode & 0o777, 0o700, "bin dir mode after a rewrite");
  assert.ok(fs.statSync(paths.npmCacheDir).isDirectory());
  assert.ok(fs.statSync(paths.npmPrefixDir).isDirectory());
});

test("writeNodeToolchain's returned paths are node-toolchain/{bin,npm-cache,npm-prefix} under userData — literals pinned with the website file", () => {



  const userDataDir = tempDir();
  const paths = writeNodeToolchain({ userDataDir, electronPath: ELECTRON, npmRoot: NPM_ROOT, platform: "darwin" });
  assert.ok(paths, "a durable electronPath always writes the toolchain");
  assert.equal(paths.toolchainDir, path.join(userDataDir, "node-toolchain"));
  assert.equal(paths.binDir, path.join(paths.toolchainDir, "bin"));
  assert.equal(paths.npmCacheDir, path.join(paths.toolchainDir, "npm-cache"));
  assert.equal(paths.npmPrefixDir, path.join(paths.toolchainDir, "npm-prefix"));
});

test("writeNodeToolchain overwrites cleanly on a second call, e.g. after the app moves", () => {
  const userDataDir = tempDir();
  writeNodeToolchain({ userDataDir, electronPath: ELECTRON, npmRoot: NPM_ROOT, platform: "darwin" });

  const movedElectron = "/Applications/Sample 2.app/Contents/MacOS/Sample";
  const paths = writeNodeToolchain({ userDataDir, electronPath: movedElectron, npmRoot: NPM_ROOT, platform: "darwin" });
  assert.ok(paths, "a durable electronPath always writes the toolchain");

  assert.deepEqual(fs.readdirSync(paths.binDir).sort(), ["node", "npm", "npx"]);
  const nodeShim = fs.readFileSync(path.join(paths.binDir, "node"), "utf8");
  assert.ok(nodeShim.includes(movedElectron), "the second write's electronPath must win");
  assert.ok(!nodeShim.includes(ELECTRON), "the first write's electronPath must not survive");
});

test("buildNodeToolchainEnv returns exactly the two contract keys, nothing else", () => {
  const env = buildNodeToolchainEnv({ ...{ toolchainDir: "/Users/someone/Library/Application Support/Sample/node-toolchain", npmRoot: NPM_ROOT }, toolchainEnvName: "SAMPLE_NODE_TOOLCHAIN_DIR", npmRootEnvName: "SAMPLE_BUNDLED_NPM_ROOT" });
  assert.deepEqual(env, {
    SAMPLE_NODE_TOOLCHAIN_DIR: "/Users/someone/Library/Application Support/Sample/node-toolchain",
    SAMPLE_BUNDLED_NPM_ROOT: NPM_ROOT,
  });
  assert.deepEqual(Object.keys(env).sort(), ["SAMPLE_BUNDLED_NPM_ROOT", "SAMPLE_NODE_TOOLCHAIN_DIR"]);
});





const DMG_ELECTRON = "/Volumes/Sample 0.1.7/Sample.app/Contents/MacOS/Sample";
const DMG_NPM_ROOT = "/Volumes/Sample 0.1.7/Sample.app/Contents/Resources/npm";
const ALL_VOLUMES_READ_ONLY = (): boolean => true;

test("writeNodeToolchain from a disk image with no earlier shims writes none and returns null", () => {
  const userDataDir = tempDir();
  const paths = writeNodeToolchain({ userDataDir, electronPath: DMG_ELECTRON, npmRoot: DMG_NPM_ROOT, platform: "darwin", isReadOnlyVolume: ALL_VOLUMES_READ_ONLY });
  assert.equal(paths, null);
  assert.equal(fs.existsSync(path.join(userDataDir, "node-toolchain", "bin", "node")), false);
});

test("writeNodeToolchain from a disk image keeps an installed copy's shims untouched and returns their paths", () => {
  const userDataDir = tempDir();
  const installedElectron = path.join(tempDir(), "Sample");
  fs.writeFileSync(installedElectron, "");
  const installed = writeNodeToolchain({ userDataDir, electronPath: installedElectron, npmRoot: NPM_ROOT, platform: "darwin" });
  assert.ok(installed);
  const before = fs.readFileSync(path.join(installed.binDir, "npx"), "utf8");

  const paths = writeNodeToolchain({ userDataDir, electronPath: DMG_ELECTRON, npmRoot: DMG_NPM_ROOT, platform: "darwin", isReadOnlyVolume: ALL_VOLUMES_READ_ONLY });

  assert.deepEqual(paths, installed);
  assert.equal(fs.readFileSync(path.join(installed.binDir, "npx"), "utf8"), before);
  for (const name of ["node", "npm", "npx"]) {
    assert.equal(fs.readFileSync(path.join(installed.binDir, name), "utf8").includes("/Volumes/"), false, name);
  }
});

test("writeNodeToolchain from a disk image does not keep shims naming an earlier disk image, and writes no new ones", () => {
  const userDataDir = tempDir();

  writeNodeToolchain({ userDataDir, electronPath: "/Volumes/Sample 0.1.6/Sample.app/Contents/MacOS/Sample", npmRoot: NPM_ROOT, platform: "darwin", isReadOnlyVolume: () => false });

  const paths = writeNodeToolchain({ userDataDir, electronPath: DMG_ELECTRON, npmRoot: DMG_NPM_ROOT, platform: "darwin", isReadOnlyVolume: ALL_VOLUMES_READ_ONLY });

  assert.equal(paths, null);
  assert.equal(fs.readFileSync(path.join(userDataDir, "node-toolchain", "bin", "node"), "utf8").includes(DMG_ELECTRON), false);
});

test("writeNodeToolchain from App Translocation is transient too", () => {
  const userDataDir = tempDir();
  const translocated = "/private/var/folders/xx/T/AppTranslocation/ABC/d/Sample.app/Contents/MacOS/Sample";
  assert.equal(writeNodeToolchain({ userDataDir, electronPath: translocated, npmRoot: NPM_ROOT, platform: "darwin" }), null);
});

test("the next launch from a real install recovers: it rewrites the shims with its own path", () => {
  const userDataDir = tempDir();
  writeNodeToolchain({ userDataDir, electronPath: DMG_ELECTRON, npmRoot: DMG_NPM_ROOT, platform: "darwin", isReadOnlyVolume: ALL_VOLUMES_READ_ONLY });
  const paths = writeNodeToolchain({ userDataDir, electronPath: ELECTRON, npmRoot: NPM_ROOT, platform: "darwin" });
  assert.ok(paths);
  assert.ok(fs.readFileSync(path.join(paths.binDir, "node"), "utf8").includes(ELECTRON));
});

test("written POSIX shims execute scripts with preserved arguments and Electron-as-node env", () => {
  const userDataDir = tempDir();
  const npmRoot = path.join(userDataDir, "bundled npm");
  fs.mkdirSync(path.join(npmRoot, "bin"), { recursive: true });
  for (const command of ["npm", "npx"]) {
    fs.writeFileSync(path.join(npmRoot, "bin", `${command}-cli.js`), `console.log(JSON.stringify({ cli: "${command}", args: process.argv.slice(2), mode: process.env.ELECTRON_RUN_AS_NODE }));`);
  }
  const paths = writeNodeToolchain({ userDataDir, electronPath: process.execPath, npmRoot, platform: process.platform });
  assert.ok(paths);
  try {
    const nodeOutput = execFileSync(path.join(paths.binDir, "node"), ["-e", 'console.log(JSON.stringify({value: 42, mode: process.env.ELECTRON_RUN_AS_NODE}))'], { encoding: "utf8" });
    assert.deepEqual(JSON.parse(nodeOutput), { value: 42, mode: "1" });
    for (const command of ["npm", "npx"]) {
      const output: string = execFileSync(path.join(paths.binDir, command), ["one argument", "--flag"], { encoding: "utf8" });
      assert.deepEqual(JSON.parse(output), { cli: command, args: ["one argument", "--flag"], mode: "1" });
    }
  } finally { fs.rmSync(userDataDir, { recursive: true, force: true }); }
});

function buildNodeToolchainShims(input: { electronPath: string; npmRoot: string; platform: NodeJS.Platform }) { return buildShims({ ...input, generatedComment: "# Generated by Sample Desktop — rewritten on every launch. Do not edit.", joinPath: ({ parts }) => path.join(...parts) }); }
function writeNodeToolchain(input: { userDataDir: string; electronPath: string; npmRoot: string; platform: NodeJS.Platform; isReadOnlyVolume?: (root: string) => boolean }) {
 const { userDataDir, isReadOnlyVolume = () => false, ...shim } = input;
 const toolchainDir=path.join(userDataDir,"node-toolchain");
 const paths={toolchainDir,binDir:path.join(toolchainDir,"bin"),npmCacheDir:path.join(toolchainDir,"npm-cache"),npmPrefixDir:path.join(toolchainDir,"npm-prefix")};
 const isTransientPath=(value:string)=>value.includes("/AppTranslocation/") || (value.startsWith("/Volumes/") && isReadOnlyVolume(value.split("/").slice(0,3).join("/")));
 const launcherNamesDurableInstall=(file:string)=>{ try { const exe=/exec '([^']+)'/.exec(fs.readFileSync(file,"utf8"))?.[1]; return !!exe && !isTransientPath(exe) && fs.existsSync(exe); } catch { return false; } };
 return writeToolchain({ ...shim, paths, filesystem: nodeFilesystem, writerPid: process.pid, joinPath: ({ parts }: { parts: string[] }) => path.join(...parts), generatedComment: "# Generated by Sample Desktop — rewritten on every launch. Do not edit.", isTransientPath: ({ executablePath }) => isTransientPath(executablePath), launcherNamesDurableInstall: ({ launcherPath }) => launcherNamesDurableInstall(launcherPath) });
}

test('caller paths and probes decide whether a transient launch preserves a durable toolchain', () => {
  const calls: string[] = [];
  const paths = { toolchainDir: '/state/tools', binDir: '/private/bin', npmCacheDir: '/cache', npmPrefixDir: '/prefix' };
  const input = { paths, filesystem: nodeFilesystem, writerPid: 9, electronPath: '/transient/exe', npmRoot: '/npm', platform: 'darwin' as const, joinPath: ({ parts }: { parts: string[] }) => path.join(...parts), generatedComment: '# A different host', isTransientPath: () => true };
  assert.equal(writeToolchain({ ...input, launcherNamesDurableInstall: ({ launcherPath: file }) => { calls.push(file); return false; } }), null);
  assert.deepEqual(writeToolchain({ ...input, launcherNamesDurableInstall: ({ launcherPath: file }) => { calls.push(file); return true; } }), paths);
  assert.deepEqual(calls, ['/private/bin/node', '/private/bin/node']);
});

test('unsafe paths fail before filesystem effects; unsafe header and env names are refused', () => {
  const calls: string[] = [];
  const dir = tempDir();
  const paths = { toolchainDir: dir, binDir: path.join(dir, 'bin'), npmCacheDir: path.join(dir, 'cache'), npmPrefixDir: path.join(dir, 'prefix') };
  const input = { paths, filesystem: { ...nodeFilesystem, mkdirSync: () => { calls.push('mkdir'); return undefined; } }, writerPid: 9, electronPath: "/bad'path", npmRoot: '/npm', platform: 'darwin' as const, joinPath: ({ parts }: { parts: string[] }) => path.join(...parts), generatedComment: '# Test', isTransientPath: () => false, launcherNamesDurableInstall: () => false };
  assert.throws(() => writeToolchain(input), /electronPath/);
  assert.deepEqual(calls, []);
  assert.throws(() => buildShims({ ...input, electronPath: '/good', generatedComment: '# heading\nmalicious' }), /one shell comment line/);
  assert.throws(() => buildNodeToolchainEnv({ toolchainDir: '/tools', npmRoot: '/npm', toolchainEnvName: 'SAME', npmRootEnvName: 'SAME' }), /valid and distinct/);
});
