import { Suspense, StrictMode } from 'react';
import { afterEach, describe, it, expect, vi } from 'vitest';
import { render, screen, fireEvent, waitFor, cleanup, act } from '@testing-library/react';
import { KitProvider, createKit, type ConfirmViewProps } from '@jini-ai/ui-kit/react';
import { createAdmin } from '../../../core/module/index.js';
import { security } from '../index.js';
import { createMemorySecurityApi, createMemoryRootKey } from '../../adapters/memory.js';
import type { CredentialProvider, CredentialSummary } from '../../models.js';
const provider: CredentialProvider = { kind: 'source-control', id: 'git', label: 'Git host', vendorLabel: 'Git vendor', category: 'source-control', tokenField: 'token', fields: [] };
const row: CredentialSummary = { kind: 'source-control', id: '1', providerId: 'git', label: 'Personal', configured: true, isDefault: true, createdAt: 'today', updatedAt: 'today' };
afterEach(cleanup);
function mount(permissions: readonly string[], options: { root?: boolean; locked?: boolean; rows?: readonly CredentialSummary[]; kit?: ReturnType<typeof createKit> } = {}) {
  const feature = security({}), api = createMemorySecurityApi({ providers: [provider], rows: options.rows ?? [] });
  const root = createMemoryRootKey(options.locked ? { status: { active: false, source: 'none', state: 'missing-with-data', keyFilePath: '/key', runtimeMode: 'local' } } : {}); const admin = createAdmin({ modules: [feature], ports: { securityApi: api, ...(options.root ? { rootKey: root } : {}) } }, { permissions });
  const { Page, tabs } = feature.react.pages.secrets;
  render(<StrictMode><KitProvider {...(options.kit ? { kit: options.kit } : {})}><feature.react.Provider admin={admin}><Suspense fallback="Loading"><Page tabs={tabs} description={admin.describe().pages[0]!} /></Suspense></feature.react.Provider></KitProvider></StrictMode>);
  return { admin, api, root };
}
describe('security React slice', () => {
  it('renders denied without grants and never loads credentials', async () => { const feature = security({}); const api = createMemorySecurityApi({}); const spy = vi.spyOn(api, 'providers'); const admin = createAdmin({ modules: [feature], ports: { securityApi: api } }); const { Page, tabs } = feature.react.pages.secrets; render(<feature.react.Provider admin={admin}><Suspense fallback="Loading"><Page tabs={tabs} description={admin.describe().pages[0]!} /></Suspense></feature.react.Provider>); expect(await screen.findByText('Permission denied')).toBeVisible(); expect(spy).not.toHaveBeenCalled(); expect(screen.queryByRole('textbox')).toBeNull(); });
  it('renders saved rows read-only without write grants, and omits optional root-key tab', async () => { mount(['security.read'], { rows: [row] }); expect(await screen.findByRole('heading', { name: 'Personal' })).toBeVisible(); expect(screen.queryByRole('button', { name: 'Edit Personal' })).toBeNull(); expect(screen.queryByRole('button', { name: 'Remove Personal' })).toBeNull(); expect(screen.queryByRole('button', { name: 'Add custom provider' })).toBeNull(); expect(screen.queryByRole('tab', { name: 'Root key' })).toBeNull(); });
  it('lazily switches root-key tab with grants and never offers reveal', async () => { mount(['security.read', 'admin.security.tokens.manage'], { root: true }); fireEvent.click(await screen.findByRole('tab', { name: 'Root key' })); expect(await screen.findByRole('button', { name: 'Create root key' })).toBeVisible(); expect(screen.queryByRole('button', { name: /reveal/i })).toBeNull(); fireEvent.click(screen.getByRole('button', { name: 'Create root key' })); await waitFor(() => expect(screen.queryByRole('button', { name: 'Create root key' })).toBeNull()); expect(screen.getByText('Root key ready')).toBeVisible(); });
  it('clears newly saved secret drafts and supports multiple named tokens', async () => { mount(['security.read', 'source-control.credentials.write']); fireEvent.click(await screen.findByRole('button', { name: 'Add Git host token' })); fireEvent.change(await screen.findByLabelText('Name'), { target: { value: 'Work token' } }); fireEvent.change(screen.getByLabelText('Access token'), { target: { value: 'NEVER_RENDER_AFTER_SAVE' } }); fireEvent.click(screen.getByRole('button', { name: 'Save' })); expect(await screen.findByRole('heading', { name: 'Work token' })).toBeVisible(); await waitFor(() => expect(screen.queryByLabelText('Access token')).toBeNull()); expect(document.body.textContent).not.toContain('NEVER_RENDER_AFTER_SAVE'); fireEvent.click(screen.getByRole('button', { name: 'Add Git host token' })); expect(await screen.findByLabelText('Access token')).toHaveValue(''); });
  it('allows host confirmation overrides and executes only through the safety controller', async () => {
    let view: ConfirmViewProps | undefined;
    function Override(props: ConfirmViewProps) { view = props; return <div role="alertdialog"><h2>{props.controller.title}</h2><span>{props.controller.body}</span><span>{props.controller.consequence}</span></div>; }
    const kit = createKit({ components: { ConfirmDialog: Override } }, { guard: 'off' }); const { api } = mount(['security.read', 'source-control.credentials.write'], { rows: [row], kit }); const remove = vi.spyOn(api.sourceControl, 'remove');
    fireEvent.click(await screen.findByRole('button', { name: 'Remove Personal' })); await screen.findByRole('alertdialog'); expect(remove).not.toHaveBeenCalled(); expect(view?.controller.agentMayConfirm).toBe(false); expect(view?.controller.confirm.onPress).toBeTypeOf('function'); act(() => { view?.controller.cancel.onPress?.({}); }); await waitFor(() => expect(screen.queryByRole('alertdialog')).toBeNull()); expect(remove).not.toHaveBeenCalled();
  });
  it('refuses fresh recovery without a typed confirmation and accepts it after preview', async () => { const { root } = mount(['security.read', 'admin.security.tokens.manage'], { root: true, locked: true }); const fresh = vi.spyOn(root, 'startFresh'); fireEvent.click(await screen.findByRole('tab', { name: 'Root key' })); fireEvent.click(await screen.findByRole('button', { name: 'Start fresh' })); const typed = await screen.findByLabelText('Type START FRESH'); const confirm = await screen.findByRole('button', { name: /^Start fresh —/ }); fireEvent.click(confirm); await waitFor(() => expect(screen.getByText("The action failed. Please try again.")).toBeVisible()); expect(fresh).not.toHaveBeenCalled(); fireEvent.change(typed, { target: { value: 'START FRESH' } }); fireEvent.click(confirm); await waitFor(() => expect(fresh).toHaveBeenCalledWith({ confirm: 'START FRESH' }, { signal: expect.any(AbortSignal) })); expect(await screen.findByText('Done. Re-enter removed credentials.')).toBeVisible(); });
});
